<?xml version="1.0" encoding="utf-8"?><Database Name="websiteDB" Class="DataWebsiteDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.VANBANDI" Member="VANBANDIs">
    <Type Name="VANBANDI">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaVanBan" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TrichYeu" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySoan" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NgayBanHanhVanBan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NoiLuuVanBan" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SoTo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgayDuyetVanBan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NguoiKyVanBan" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ChucVuNguoiKy" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DonViNhan" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="NoiDungVanBan" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="urlNoiDungVanBan" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="VanBanLienQuanVanBan" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="urlVanBanLienQuanVanBan" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NguoiDungId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CongViecId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LoaiVanBanId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LuuTruId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TrangThaiVanBanId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QuyenId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoVanBanId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KeyWord" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.CHUCVU" Member="CHUCVUs">
    <Type Name="CHUCVU">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenChucVu" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MaChucVu" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="KeyWord" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.CONGVIEC" Member="CONGVIECs">
    <Type Name="CONGVIEC">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenCongViec" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="MaCongViec" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="NgayTao" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NgayHoanThanhDuKien" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NgayHoanThanhThucTe" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NguoiDungId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PhongBanId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="KeyWord" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIVANBAN" Member="LOAIVANBANs">
    <Type Name="LOAIVANBAN">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLoaiVanBan" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MaLoaiVanBan" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="KeyWord" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.LUUTRU" Member="LUUTRUs">
    <Type Name="LUUTRU">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenLuuTru" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MaLuuTru" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianLuu" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NoiLuu" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="TenKho" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MaKho" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TenKe" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MaKe" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="TenHop" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MaHop" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="KeyWord" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.NGUOIDUNG" Member="NGUOIDUNGs">
    <Type Name="NGUOIDUNG">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaNhanVien" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="HoVaTen" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="QueQuan" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SoDienThoai" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="NgayBatDauLamViec" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="MatKhau" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ChucVuId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QuyenId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PhongBanId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KeyWord" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.PHANQUYEN" Member="PHANQUYENs">
    <Type Name="PHANQUYEN">
      <Column Name="NguoiDungId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuyenHanId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHONGBAN" Member="PHONGBANs">
    <Type Name="PHONGBAN">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenPhongBan" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MaPhongBan" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SoNhanVien" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="KeyWord" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.QUYENHAN" Member="QUYENHANs">
    <Type Name="QUYENHAN">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenQuyenHan" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MaQuyen" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NgayBatDau" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NgayKetThuc" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="KeyWord" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.SOVANBAN" Member="SOVANBANs">
    <Type Name="SOVANBAN">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenSoVanBan" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="MaSoVanBan" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NgayTaoSo" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NgayDongSo" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="KeyWord" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.TRANGTHAIVANBAN" Member="TRANGTHAIVANBANs">
    <Type Name="TRANGTHAIVANBAN">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenTrangThai" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="MaTrangThai" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="KeyWord" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.URLVANBANDEN" Member="URLVANBANDENs">
    <Type Name="URLVANBANDEN">
      <Column Name="MaVanBan" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TenFile" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="urlFile" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.VANBANDEN" Member="VANBANDENs">
    <Type Name="VANBANDEN">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaVanBan" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="TrichYeu" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="NgayNhan" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NgayBanHanhVanBan" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="NoiLuuVanBan" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SoTo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgayDuyetVanBan" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="NguoiKyVanBan" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="ChucVuNguoiKy" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DonViGui" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="NoiDungVanBan" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="urlNoiDungVanBan" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="VanBanLienQuanVanBan" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="urlVanBanLienQuanVanBan" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NguoiDungId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CongViecId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LoaiVanBanId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LuuTruId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TrangThaiVanBanId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="QuyenId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SoVanBanId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KeyWord" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>