#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An_CNPM.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="websiteDB")]
	public partial class DataWebsiteDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertVANBANDI(VANBANDI instance);
    partial void UpdateVANBANDI(VANBANDI instance);
    partial void DeleteVANBANDI(VANBANDI instance);
    partial void InsertCHUCVU(CHUCVU instance);
    partial void UpdateCHUCVU(CHUCVU instance);
    partial void DeleteCHUCVU(CHUCVU instance);
    partial void InsertCONGVIEC(CONGVIEC instance);
    partial void UpdateCONGVIEC(CONGVIEC instance);
    partial void DeleteCONGVIEC(CONGVIEC instance);
    partial void InsertLOAIVANBAN(LOAIVANBAN instance);
    partial void UpdateLOAIVANBAN(LOAIVANBAN instance);
    partial void DeleteLOAIVANBAN(LOAIVANBAN instance);
    partial void InsertLUUTRU(LUUTRU instance);
    partial void UpdateLUUTRU(LUUTRU instance);
    partial void DeleteLUUTRU(LUUTRU instance);
    partial void InsertNGUOIDUNG(NGUOIDUNG instance);
    partial void UpdateNGUOIDUNG(NGUOIDUNG instance);
    partial void DeleteNGUOIDUNG(NGUOIDUNG instance);
    partial void InsertPHONGBAN(PHONGBAN instance);
    partial void UpdatePHONGBAN(PHONGBAN instance);
    partial void DeletePHONGBAN(PHONGBAN instance);
    partial void InsertQUYENHAN(QUYENHAN instance);
    partial void UpdateQUYENHAN(QUYENHAN instance);
    partial void DeleteQUYENHAN(QUYENHAN instance);
    partial void InsertSOVANBAN(SOVANBAN instance);
    partial void UpdateSOVANBAN(SOVANBAN instance);
    partial void DeleteSOVANBAN(SOVANBAN instance);
    partial void InsertTRANGTHAIVANBAN(TRANGTHAIVANBAN instance);
    partial void UpdateTRANGTHAIVANBAN(TRANGTHAIVANBAN instance);
    partial void DeleteTRANGTHAIVANBAN(TRANGTHAIVANBAN instance);
    partial void InsertVANBANDEN(VANBANDEN instance);
    partial void UpdateVANBANDEN(VANBANDEN instance);
    partial void DeleteVANBANDEN(VANBANDEN instance);
    #endregion
		
		public DataWebsiteDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataWebsiteDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataWebsiteDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataWebsiteDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VANBANDI> VANBANDIs
		{
			get
			{
				return this.GetTable<VANBANDI>();
			}
		}
		
		public System.Data.Linq.Table<CHUCVU> CHUCVUs
		{
			get
			{
				return this.GetTable<CHUCVU>();
			}
		}
		
		public System.Data.Linq.Table<CONGVIEC> CONGVIECs
		{
			get
			{
				return this.GetTable<CONGVIEC>();
			}
		}
		
		public System.Data.Linq.Table<LOAIVANBAN> LOAIVANBANs
		{
			get
			{
				return this.GetTable<LOAIVANBAN>();
			}
		}
		
		public System.Data.Linq.Table<LUUTRU> LUUTRUs
		{
			get
			{
				return this.GetTable<LUUTRU>();
			}
		}
		
		public System.Data.Linq.Table<NGUOIDUNG> NGUOIDUNGs
		{
			get
			{
				return this.GetTable<NGUOIDUNG>();
			}
		}
		
		public System.Data.Linq.Table<PHANQUYEN> PHANQUYENs
		{
			get
			{
				return this.GetTable<PHANQUYEN>();
			}
		}
		
		public System.Data.Linq.Table<PHONGBAN> PHONGBANs
		{
			get
			{
				return this.GetTable<PHONGBAN>();
			}
		}
		
		public System.Data.Linq.Table<QUYENHAN> QUYENHANs
		{
			get
			{
				return this.GetTable<QUYENHAN>();
			}
		}
		
		public System.Data.Linq.Table<SOVANBAN> SOVANBANs
		{
			get
			{
				return this.GetTable<SOVANBAN>();
			}
		}
		
		public System.Data.Linq.Table<TRANGTHAIVANBAN> TRANGTHAIVANBANs
		{
			get
			{
				return this.GetTable<TRANGTHAIVANBAN>();
			}
		}
		
		public System.Data.Linq.Table<URLVANBANDEN> URLVANBANDENs
		{
			get
			{
				return this.GetTable<URLVANBANDEN>();
			}
		}
		
		public System.Data.Linq.Table<VANBANDEN> VANBANDENs
		{
			get
			{
				return this.GetTable<VANBANDEN>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VANBANDI")]
	public partial class VANBANDI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _MaVanBan;
		
		private string _TrichYeu;
		
		private System.DateTime _NgaySoan;
		
		private System.Nullable<System.DateTime> _NgayBanHanhVanBan;
		
		private string _NoiLuuVanBan;
		
		private int _SoTo;
		
		private System.Nullable<System.DateTime> _NgayDuyetVanBan;
		
		private string _NguoiKyVanBan;
		
		private string _ChucVuNguoiKy;
		
		private string _DonViNhan;
		
		private string _NoiDungVanBan;
		
		private string _urlNoiDungVanBan;
		
		private string _VanBanLienQuanVanBan;
		
		private string _urlVanBanLienQuanVanBan;
		
		private string _GhiChu;
		
		private int _NguoiDungId;
		
		private int _CongViecId;
		
		private int _LoaiVanBanId;
		
		private int _LuuTruId;
		
		private int _TrangThaiVanBanId;
		
		private int _QuyenId;
		
		private int _SoVanBanId;
		
		private string _KeyWord;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMaVanBanChanging(string value);
    partial void OnMaVanBanChanged();
    partial void OnTrichYeuChanging(string value);
    partial void OnTrichYeuChanged();
    partial void OnNgaySoanChanging(System.DateTime value);
    partial void OnNgaySoanChanged();
    partial void OnNgayBanHanhVanBanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayBanHanhVanBanChanged();
    partial void OnNoiLuuVanBanChanging(string value);
    partial void OnNoiLuuVanBanChanged();
    partial void OnSoToChanging(int value);
    partial void OnSoToChanged();
    partial void OnNgayDuyetVanBanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDuyetVanBanChanged();
    partial void OnNguoiKyVanBanChanging(string value);
    partial void OnNguoiKyVanBanChanged();
    partial void OnChucVuNguoiKyChanging(string value);
    partial void OnChucVuNguoiKyChanged();
    partial void OnDonViNhanChanging(string value);
    partial void OnDonViNhanChanged();
    partial void OnNoiDungVanBanChanging(string value);
    partial void OnNoiDungVanBanChanged();
    partial void OnurlNoiDungVanBanChanging(string value);
    partial void OnurlNoiDungVanBanChanged();
    partial void OnVanBanLienQuanVanBanChanging(string value);
    partial void OnVanBanLienQuanVanBanChanged();
    partial void OnurlVanBanLienQuanVanBanChanging(string value);
    partial void OnurlVanBanLienQuanVanBanChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnNguoiDungIdChanging(int value);
    partial void OnNguoiDungIdChanged();
    partial void OnCongViecIdChanging(int value);
    partial void OnCongViecIdChanged();
    partial void OnLoaiVanBanIdChanging(int value);
    partial void OnLoaiVanBanIdChanged();
    partial void OnLuuTruIdChanging(int value);
    partial void OnLuuTruIdChanged();
    partial void OnTrangThaiVanBanIdChanging(int value);
    partial void OnTrangThaiVanBanIdChanged();
    partial void OnQuyenIdChanging(int value);
    partial void OnQuyenIdChanged();
    partial void OnSoVanBanIdChanging(int value);
    partial void OnSoVanBanIdChanged();
    partial void OnKeyWordChanging(string value);
    partial void OnKeyWordChanged();
    #endregion
		
		public VANBANDI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVanBan", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaVanBan
		{
			get
			{
				return this._MaVanBan;
			}
			set
			{
				if ((this._MaVanBan != value))
				{
					this.OnMaVanBanChanging(value);
					this.SendPropertyChanging();
					this._MaVanBan = value;
					this.SendPropertyChanged("MaVanBan");
					this.OnMaVanBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrichYeu", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TrichYeu
		{
			get
			{
				return this._TrichYeu;
			}
			set
			{
				if ((this._TrichYeu != value))
				{
					this.OnTrichYeuChanging(value);
					this.SendPropertyChanging();
					this._TrichYeu = value;
					this.SendPropertyChanged("TrichYeu");
					this.OnTrichYeuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySoan", DbType="DateTime NOT NULL")]
		public System.DateTime NgaySoan
		{
			get
			{
				return this._NgaySoan;
			}
			set
			{
				if ((this._NgaySoan != value))
				{
					this.OnNgaySoanChanging(value);
					this.SendPropertyChanging();
					this._NgaySoan = value;
					this.SendPropertyChanged("NgaySoan");
					this.OnNgaySoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBanHanhVanBan", DbType="Date")]
		public System.Nullable<System.DateTime> NgayBanHanhVanBan
		{
			get
			{
				return this._NgayBanHanhVanBan;
			}
			set
			{
				if ((this._NgayBanHanhVanBan != value))
				{
					this.OnNgayBanHanhVanBanChanging(value);
					this.SendPropertyChanging();
					this._NgayBanHanhVanBan = value;
					this.SendPropertyChanged("NgayBanHanhVanBan");
					this.OnNgayBanHanhVanBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiLuuVanBan", DbType="NVarChar(255)")]
		public string NoiLuuVanBan
		{
			get
			{
				return this._NoiLuuVanBan;
			}
			set
			{
				if ((this._NoiLuuVanBan != value))
				{
					this.OnNoiLuuVanBanChanging(value);
					this.SendPropertyChanging();
					this._NoiLuuVanBan = value;
					this.SendPropertyChanged("NoiLuuVanBan");
					this.OnNoiLuuVanBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTo", DbType="Int NOT NULL")]
		public int SoTo
		{
			get
			{
				return this._SoTo;
			}
			set
			{
				if ((this._SoTo != value))
				{
					this.OnSoToChanging(value);
					this.SendPropertyChanging();
					this._SoTo = value;
					this.SendPropertyChanged("SoTo");
					this.OnSoToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDuyetVanBan", DbType="Date")]
		public System.Nullable<System.DateTime> NgayDuyetVanBan
		{
			get
			{
				return this._NgayDuyetVanBan;
			}
			set
			{
				if ((this._NgayDuyetVanBan != value))
				{
					this.OnNgayDuyetVanBanChanging(value);
					this.SendPropertyChanging();
					this._NgayDuyetVanBan = value;
					this.SendPropertyChanged("NgayDuyetVanBan");
					this.OnNgayDuyetVanBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiKyVanBan", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NguoiKyVanBan
		{
			get
			{
				return this._NguoiKyVanBan;
			}
			set
			{
				if ((this._NguoiKyVanBan != value))
				{
					this.OnNguoiKyVanBanChanging(value);
					this.SendPropertyChanging();
					this._NguoiKyVanBan = value;
					this.SendPropertyChanged("NguoiKyVanBan");
					this.OnNguoiKyVanBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVuNguoiKy", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ChucVuNguoiKy
		{
			get
			{
				return this._ChucVuNguoiKy;
			}
			set
			{
				if ((this._ChucVuNguoiKy != value))
				{
					this.OnChucVuNguoiKyChanging(value);
					this.SendPropertyChanging();
					this._ChucVuNguoiKy = value;
					this.SendPropertyChanged("ChucVuNguoiKy");
					this.OnChucVuNguoiKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonViNhan", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string DonViNhan
		{
			get
			{
				return this._DonViNhan;
			}
			set
			{
				if ((this._DonViNhan != value))
				{
					this.OnDonViNhanChanging(value);
					this.SendPropertyChanging();
					this._DonViNhan = value;
					this.SendPropertyChanged("DonViNhan");
					this.OnDonViNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungVanBan", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string NoiDungVanBan
		{
			get
			{
				return this._NoiDungVanBan;
			}
			set
			{
				if ((this._NoiDungVanBan != value))
				{
					this.OnNoiDungVanBanChanging(value);
					this.SendPropertyChanging();
					this._NoiDungVanBan = value;
					this.SendPropertyChanged("NoiDungVanBan");
					this.OnNoiDungVanBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlNoiDungVanBan", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string urlNoiDungVanBan
		{
			get
			{
				return this._urlNoiDungVanBan;
			}
			set
			{
				if ((this._urlNoiDungVanBan != value))
				{
					this.OnurlNoiDungVanBanChanging(value);
					this.SendPropertyChanging();
					this._urlNoiDungVanBan = value;
					this.SendPropertyChanged("urlNoiDungVanBan");
					this.OnurlNoiDungVanBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VanBanLienQuanVanBan", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string VanBanLienQuanVanBan
		{
			get
			{
				return this._VanBanLienQuanVanBan;
			}
			set
			{
				if ((this._VanBanLienQuanVanBan != value))
				{
					this.OnVanBanLienQuanVanBanChanging(value);
					this.SendPropertyChanging();
					this._VanBanLienQuanVanBan = value;
					this.SendPropertyChanged("VanBanLienQuanVanBan");
					this.OnVanBanLienQuanVanBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlVanBanLienQuanVanBan", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string urlVanBanLienQuanVanBan
		{
			get
			{
				return this._urlVanBanLienQuanVanBan;
			}
			set
			{
				if ((this._urlVanBanLienQuanVanBan != value))
				{
					this.OnurlVanBanLienQuanVanBanChanging(value);
					this.SendPropertyChanging();
					this._urlVanBanLienQuanVanBan = value;
					this.SendPropertyChanged("urlVanBanLienQuanVanBan");
					this.OnurlVanBanLienQuanVanBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(255)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiDungId", DbType="Int NOT NULL")]
		public int NguoiDungId
		{
			get
			{
				return this._NguoiDungId;
			}
			set
			{
				if ((this._NguoiDungId != value))
				{
					this.OnNguoiDungIdChanging(value);
					this.SendPropertyChanging();
					this._NguoiDungId = value;
					this.SendPropertyChanged("NguoiDungId");
					this.OnNguoiDungIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CongViecId", DbType="Int NOT NULL")]
		public int CongViecId
		{
			get
			{
				return this._CongViecId;
			}
			set
			{
				if ((this._CongViecId != value))
				{
					this.OnCongViecIdChanging(value);
					this.SendPropertyChanging();
					this._CongViecId = value;
					this.SendPropertyChanged("CongViecId");
					this.OnCongViecIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiVanBanId", DbType="Int NOT NULL")]
		public int LoaiVanBanId
		{
			get
			{
				return this._LoaiVanBanId;
			}
			set
			{
				if ((this._LoaiVanBanId != value))
				{
					this.OnLoaiVanBanIdChanging(value);
					this.SendPropertyChanging();
					this._LoaiVanBanId = value;
					this.SendPropertyChanged("LoaiVanBanId");
					this.OnLoaiVanBanIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuuTruId", DbType="Int NOT NULL")]
		public int LuuTruId
		{
			get
			{
				return this._LuuTruId;
			}
			set
			{
				if ((this._LuuTruId != value))
				{
					this.OnLuuTruIdChanging(value);
					this.SendPropertyChanging();
					this._LuuTruId = value;
					this.SendPropertyChanged("LuuTruId");
					this.OnLuuTruIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiVanBanId", DbType="Int NOT NULL")]
		public int TrangThaiVanBanId
		{
			get
			{
				return this._TrangThaiVanBanId;
			}
			set
			{
				if ((this._TrangThaiVanBanId != value))
				{
					this.OnTrangThaiVanBanIdChanging(value);
					this.SendPropertyChanging();
					this._TrangThaiVanBanId = value;
					this.SendPropertyChanged("TrangThaiVanBanId");
					this.OnTrangThaiVanBanIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuyenId", DbType="Int NOT NULL")]
		public int QuyenId
		{
			get
			{
				return this._QuyenId;
			}
			set
			{
				if ((this._QuyenId != value))
				{
					this.OnQuyenIdChanging(value);
					this.SendPropertyChanging();
					this._QuyenId = value;
					this.SendPropertyChanged("QuyenId");
					this.OnQuyenIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoVanBanId", DbType="Int NOT NULL")]
		public int SoVanBanId
		{
			get
			{
				return this._SoVanBanId;
			}
			set
			{
				if ((this._SoVanBanId != value))
				{
					this.OnSoVanBanIdChanging(value);
					this.SendPropertyChanging();
					this._SoVanBanId = value;
					this.SendPropertyChanged("SoVanBanId");
					this.OnSoVanBanIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyWord", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string KeyWord
		{
			get
			{
				return this._KeyWord;
			}
			set
			{
				if ((this._KeyWord != value))
				{
					this.OnKeyWordChanging(value);
					this.SendPropertyChanging();
					this._KeyWord = value;
					this.SendPropertyChanged("KeyWord");
					this.OnKeyWordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHUCVU")]
	public partial class CHUCVU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TenChucVu;
		
		private string _MaChucVu;
		
		private string _GhiChu;
		
		private string _KeyWord;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTenChucVuChanging(string value);
    partial void OnTenChucVuChanged();
    partial void OnMaChucVuChanging(string value);
    partial void OnMaChucVuChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnKeyWordChanging(string value);
    partial void OnKeyWordChanged();
    #endregion
		
		public CHUCVU()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenChucVu", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenChucVu
		{
			get
			{
				return this._TenChucVu;
			}
			set
			{
				if ((this._TenChucVu != value))
				{
					this.OnTenChucVuChanging(value);
					this.SendPropertyChanging();
					this._TenChucVu = value;
					this.SendPropertyChanged("TenChucVu");
					this.OnTenChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChucVu", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MaChucVu
		{
			get
			{
				return this._MaChucVu;
			}
			set
			{
				if ((this._MaChucVu != value))
				{
					this.OnMaChucVuChanging(value);
					this.SendPropertyChanging();
					this._MaChucVu = value;
					this.SendPropertyChanged("MaChucVu");
					this.OnMaChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(255)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyWord", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string KeyWord
		{
			get
			{
				return this._KeyWord;
			}
			set
			{
				if ((this._KeyWord != value))
				{
					this.OnKeyWordChanging(value);
					this.SendPropertyChanging();
					this._KeyWord = value;
					this.SendPropertyChanged("KeyWord");
					this.OnKeyWordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CONGVIEC")]
	public partial class CONGVIEC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TenCongViec;
		
		private string _MaCongViec;
		
		private System.DateTime _NgayTao;
		
		private System.DateTime _NgayHoanThanhDuKien;
		
		private System.Nullable<System.DateTime> _NgayHoanThanhThucTe;
		
		private int _NguoiDungId;
		
		private int _PhongBanId;
		
		private string _GhiChu;
		
		private string _KeyWord;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTenCongViecChanging(string value);
    partial void OnTenCongViecChanged();
    partial void OnMaCongViecChanging(string value);
    partial void OnMaCongViecChanged();
    partial void OnNgayTaoChanging(System.DateTime value);
    partial void OnNgayTaoChanged();
    partial void OnNgayHoanThanhDuKienChanging(System.DateTime value);
    partial void OnNgayHoanThanhDuKienChanged();
    partial void OnNgayHoanThanhThucTeChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayHoanThanhThucTeChanged();
    partial void OnNguoiDungIdChanging(int value);
    partial void OnNguoiDungIdChanged();
    partial void OnPhongBanIdChanging(int value);
    partial void OnPhongBanIdChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnKeyWordChanging(string value);
    partial void OnKeyWordChanged();
    #endregion
		
		public CONGVIEC()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCongViec", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TenCongViec
		{
			get
			{
				return this._TenCongViec;
			}
			set
			{
				if ((this._TenCongViec != value))
				{
					this.OnTenCongViecChanging(value);
					this.SendPropertyChanging();
					this._TenCongViec = value;
					this.SendPropertyChanged("TenCongViec");
					this.OnTenCongViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCongViec", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string MaCongViec
		{
			get
			{
				return this._MaCongViec;
			}
			set
			{
				if ((this._MaCongViec != value))
				{
					this.OnMaCongViecChanging(value);
					this.SendPropertyChanging();
					this._MaCongViec = value;
					this.SendPropertyChanged("MaCongViec");
					this.OnMaCongViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTao", DbType="Date NOT NULL")]
		public System.DateTime NgayTao
		{
			get
			{
				return this._NgayTao;
			}
			set
			{
				if ((this._NgayTao != value))
				{
					this.OnNgayTaoChanging(value);
					this.SendPropertyChanging();
					this._NgayTao = value;
					this.SendPropertyChanged("NgayTao");
					this.OnNgayTaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHoanThanhDuKien", DbType="DateTime NOT NULL")]
		public System.DateTime NgayHoanThanhDuKien
		{
			get
			{
				return this._NgayHoanThanhDuKien;
			}
			set
			{
				if ((this._NgayHoanThanhDuKien != value))
				{
					this.OnNgayHoanThanhDuKienChanging(value);
					this.SendPropertyChanging();
					this._NgayHoanThanhDuKien = value;
					this.SendPropertyChanged("NgayHoanThanhDuKien");
					this.OnNgayHoanThanhDuKienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHoanThanhThucTe", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayHoanThanhThucTe
		{
			get
			{
				return this._NgayHoanThanhThucTe;
			}
			set
			{
				if ((this._NgayHoanThanhThucTe != value))
				{
					this.OnNgayHoanThanhThucTeChanging(value);
					this.SendPropertyChanging();
					this._NgayHoanThanhThucTe = value;
					this.SendPropertyChanged("NgayHoanThanhThucTe");
					this.OnNgayHoanThanhThucTeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiDungId", DbType="Int NOT NULL")]
		public int NguoiDungId
		{
			get
			{
				return this._NguoiDungId;
			}
			set
			{
				if ((this._NguoiDungId != value))
				{
					this.OnNguoiDungIdChanging(value);
					this.SendPropertyChanging();
					this._NguoiDungId = value;
					this.SendPropertyChanged("NguoiDungId");
					this.OnNguoiDungIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhongBanId", DbType="Int NOT NULL")]
		public int PhongBanId
		{
			get
			{
				return this._PhongBanId;
			}
			set
			{
				if ((this._PhongBanId != value))
				{
					this.OnPhongBanIdChanging(value);
					this.SendPropertyChanging();
					this._PhongBanId = value;
					this.SendPropertyChanged("PhongBanId");
					this.OnPhongBanIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(255)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyWord", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string KeyWord
		{
			get
			{
				return this._KeyWord;
			}
			set
			{
				if ((this._KeyWord != value))
				{
					this.OnKeyWordChanging(value);
					this.SendPropertyChanging();
					this._KeyWord = value;
					this.SendPropertyChanged("KeyWord");
					this.OnKeyWordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIVANBAN")]
	public partial class LOAIVANBAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TenLoaiVanBan;
		
		private string _MaLoaiVanBan;
		
		private string _GhiChu;
		
		private string _KeyWord;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTenLoaiVanBanChanging(string value);
    partial void OnTenLoaiVanBanChanged();
    partial void OnMaLoaiVanBanChanging(string value);
    partial void OnMaLoaiVanBanChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnKeyWordChanging(string value);
    partial void OnKeyWordChanged();
    #endregion
		
		public LOAIVANBAN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiVanBan", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenLoaiVanBan
		{
			get
			{
				return this._TenLoaiVanBan;
			}
			set
			{
				if ((this._TenLoaiVanBan != value))
				{
					this.OnTenLoaiVanBanChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiVanBan = value;
					this.SendPropertyChanged("TenLoaiVanBan");
					this.OnTenLoaiVanBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiVanBan", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MaLoaiVanBan
		{
			get
			{
				return this._MaLoaiVanBan;
			}
			set
			{
				if ((this._MaLoaiVanBan != value))
				{
					this.OnMaLoaiVanBanChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiVanBan = value;
					this.SendPropertyChanged("MaLoaiVanBan");
					this.OnMaLoaiVanBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(255)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyWord", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string KeyWord
		{
			get
			{
				return this._KeyWord;
			}
			set
			{
				if ((this._KeyWord != value))
				{
					this.OnKeyWordChanging(value);
					this.SendPropertyChanging();
					this._KeyWord = value;
					this.SendPropertyChanged("KeyWord");
					this.OnKeyWordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LUUTRU")]
	public partial class LUUTRU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TenLuuTru;
		
		private string _MaLuuTru;
		
		private int _ThoiGianLuu;
		
		private string _NoiLuu;
		
		private string _TenKho;
		
		private string _MaKho;
		
		private string _TenKe;
		
		private string _MaKe;
		
		private string _TenHop;
		
		private string _MaHop;
		
		private string _KeyWord;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTenLuuTruChanging(string value);
    partial void OnTenLuuTruChanged();
    partial void OnMaLuuTruChanging(string value);
    partial void OnMaLuuTruChanged();
    partial void OnThoiGianLuuChanging(int value);
    partial void OnThoiGianLuuChanged();
    partial void OnNoiLuuChanging(string value);
    partial void OnNoiLuuChanged();
    partial void OnTenKhoChanging(string value);
    partial void OnTenKhoChanged();
    partial void OnMaKhoChanging(string value);
    partial void OnMaKhoChanged();
    partial void OnTenKeChanging(string value);
    partial void OnTenKeChanged();
    partial void OnMaKeChanging(string value);
    partial void OnMaKeChanged();
    partial void OnTenHopChanging(string value);
    partial void OnTenHopChanged();
    partial void OnMaHopChanging(string value);
    partial void OnMaHopChanged();
    partial void OnKeyWordChanging(string value);
    partial void OnKeyWordChanged();
    #endregion
		
		public LUUTRU()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLuuTru", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenLuuTru
		{
			get
			{
				return this._TenLuuTru;
			}
			set
			{
				if ((this._TenLuuTru != value))
				{
					this.OnTenLuuTruChanging(value);
					this.SendPropertyChanging();
					this._TenLuuTru = value;
					this.SendPropertyChanged("TenLuuTru");
					this.OnTenLuuTruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLuuTru", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MaLuuTru
		{
			get
			{
				return this._MaLuuTru;
			}
			set
			{
				if ((this._MaLuuTru != value))
				{
					this.OnMaLuuTruChanging(value);
					this.SendPropertyChanging();
					this._MaLuuTru = value;
					this.SendPropertyChanged("MaLuuTru");
					this.OnMaLuuTruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianLuu", DbType="Int NOT NULL")]
		public int ThoiGianLuu
		{
			get
			{
				return this._ThoiGianLuu;
			}
			set
			{
				if ((this._ThoiGianLuu != value))
				{
					this.OnThoiGianLuuChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianLuu = value;
					this.SendPropertyChanged("ThoiGianLuu");
					this.OnThoiGianLuuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiLuu", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string NoiLuu
		{
			get
			{
				return this._NoiLuu;
			}
			set
			{
				if ((this._NoiLuu != value))
				{
					this.OnNoiLuuChanging(value);
					this.SendPropertyChanging();
					this._NoiLuu = value;
					this.SendPropertyChanged("NoiLuu");
					this.OnNoiLuuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKho", DbType="NVarChar(100)")]
		public string TenKho
		{
			get
			{
				return this._TenKho;
			}
			set
			{
				if ((this._TenKho != value))
				{
					this.OnTenKhoChanging(value);
					this.SendPropertyChanging();
					this._TenKho = value;
					this.SendPropertyChanged("TenKho");
					this.OnTenKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKho", DbType="VarChar(20)")]
		public string MaKho
		{
			get
			{
				return this._MaKho;
			}
			set
			{
				if ((this._MaKho != value))
				{
					this.OnMaKhoChanging(value);
					this.SendPropertyChanging();
					this._MaKho = value;
					this.SendPropertyChanged("MaKho");
					this.OnMaKhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKe", DbType="NVarChar(100)")]
		public string TenKe
		{
			get
			{
				return this._TenKe;
			}
			set
			{
				if ((this._TenKe != value))
				{
					this.OnTenKeChanging(value);
					this.SendPropertyChanging();
					this._TenKe = value;
					this.SendPropertyChanged("TenKe");
					this.OnTenKeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKe", DbType="VarChar(20)")]
		public string MaKe
		{
			get
			{
				return this._MaKe;
			}
			set
			{
				if ((this._MaKe != value))
				{
					this.OnMaKeChanging(value);
					this.SendPropertyChanging();
					this._MaKe = value;
					this.SendPropertyChanged("MaKe");
					this.OnMaKeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHop", DbType="NVarChar(100)")]
		public string TenHop
		{
			get
			{
				return this._TenHop;
			}
			set
			{
				if ((this._TenHop != value))
				{
					this.OnTenHopChanging(value);
					this.SendPropertyChanging();
					this._TenHop = value;
					this.SendPropertyChanged("TenHop");
					this.OnTenHopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHop", DbType="VarChar(20)")]
		public string MaHop
		{
			get
			{
				return this._MaHop;
			}
			set
			{
				if ((this._MaHop != value))
				{
					this.OnMaHopChanging(value);
					this.SendPropertyChanging();
					this._MaHop = value;
					this.SendPropertyChanged("MaHop");
					this.OnMaHopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyWord", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string KeyWord
		{
			get
			{
				return this._KeyWord;
			}
			set
			{
				if ((this._KeyWord != value))
				{
					this.OnKeyWordChanging(value);
					this.SendPropertyChanging();
					this._KeyWord = value;
					this.SendPropertyChanged("KeyWord");
					this.OnKeyWordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NGUOIDUNG")]
	public partial class NGUOIDUNG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _MaNhanVien;
		
		private string _HoVaTen;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _DiaChi;
		
		private string _QueQuan;
		
		private string _Email;
		
		private string _SoDienThoai;
		
		private System.Nullable<System.DateTime> _NgayBatDauLamViec;
		
		private string _MatKhau;
		
		private int _ChucVuId;
		
		private int _QuyenId;
		
		private int _PhongBanId;
		
		private string _KeyWord;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMaNhanVienChanging(string value);
    partial void OnMaNhanVienChanged();
    partial void OnHoVaTenChanging(string value);
    partial void OnHoVaTenChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnQueQuanChanging(string value);
    partial void OnQueQuanChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnNgayBatDauLamViecChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayBatDauLamViecChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnChucVuIdChanging(int value);
    partial void OnChucVuIdChanged();
    partial void OnQuyenIdChanging(int value);
    partial void OnQuyenIdChanged();
    partial void OnPhongBanIdChanging(int value);
    partial void OnPhongBanIdChanged();
    partial void OnKeyWordChanging(string value);
    partial void OnKeyWordChanged();
    #endregion
		
		public NGUOIDUNG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoVaTen", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string HoVaTen
		{
			get
			{
				return this._HoVaTen;
			}
			set
			{
				if ((this._HoVaTen != value))
				{
					this.OnHoVaTenChanging(value);
					this.SendPropertyChanging();
					this._HoVaTen = value;
					this.SendPropertyChanged("HoVaTen");
					this.OnHoVaTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(255)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QueQuan", DbType="NVarChar(255)")]
		public string QueQuan
		{
			get
			{
				return this._QueQuan;
			}
			set
			{
				if ((this._QueQuan != value))
				{
					this.OnQueQuanChanging(value);
					this.SendPropertyChanging();
					this._QueQuan = value;
					this.SendPropertyChanged("QueQuan");
					this.OnQueQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBatDauLamViec", DbType="Date")]
		public System.Nullable<System.DateTime> NgayBatDauLamViec
		{
			get
			{
				return this._NgayBatDauLamViec;
			}
			set
			{
				if ((this._NgayBatDauLamViec != value))
				{
					this.OnNgayBatDauLamViecChanging(value);
					this.SendPropertyChanging();
					this._NgayBatDauLamViec = value;
					this.SendPropertyChanged("NgayBatDauLamViec");
					this.OnNgayBatDauLamViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVuId", DbType="Int NOT NULL")]
		public int ChucVuId
		{
			get
			{
				return this._ChucVuId;
			}
			set
			{
				if ((this._ChucVuId != value))
				{
					this.OnChucVuIdChanging(value);
					this.SendPropertyChanging();
					this._ChucVuId = value;
					this.SendPropertyChanged("ChucVuId");
					this.OnChucVuIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuyenId", DbType="Int NOT NULL")]
		public int QuyenId
		{
			get
			{
				return this._QuyenId;
			}
			set
			{
				if ((this._QuyenId != value))
				{
					this.OnQuyenIdChanging(value);
					this.SendPropertyChanging();
					this._QuyenId = value;
					this.SendPropertyChanged("QuyenId");
					this.OnQuyenIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhongBanId", DbType="Int NOT NULL")]
		public int PhongBanId
		{
			get
			{
				return this._PhongBanId;
			}
			set
			{
				if ((this._PhongBanId != value))
				{
					this.OnPhongBanIdChanging(value);
					this.SendPropertyChanging();
					this._PhongBanId = value;
					this.SendPropertyChanged("PhongBanId");
					this.OnPhongBanIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyWord", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string KeyWord
		{
			get
			{
				return this._KeyWord;
			}
			set
			{
				if ((this._KeyWord != value))
				{
					this.OnKeyWordChanging(value);
					this.SendPropertyChanging();
					this._KeyWord = value;
					this.SendPropertyChanged("KeyWord");
					this.OnKeyWordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHANQUYEN")]
	public partial class PHANQUYEN
	{
		
		private System.Nullable<int> _NguoiDungId;
		
		private System.Nullable<int> _QuyenHanId;
		
		public PHANQUYEN()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiDungId", DbType="Int")]
		public System.Nullable<int> NguoiDungId
		{
			get
			{
				return this._NguoiDungId;
			}
			set
			{
				if ((this._NguoiDungId != value))
				{
					this._NguoiDungId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuyenHanId", DbType="Int")]
		public System.Nullable<int> QuyenHanId
		{
			get
			{
				return this._QuyenHanId;
			}
			set
			{
				if ((this._QuyenHanId != value))
				{
					this._QuyenHanId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHONGBAN")]
	public partial class PHONGBAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TenPhongBan;
		
		private string _MaPhongBan;
		
		private int _SoNhanVien;
		
		private string _GhiChu;
		
		private string _KeyWord;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTenPhongBanChanging(string value);
    partial void OnTenPhongBanChanged();
    partial void OnMaPhongBanChanging(string value);
    partial void OnMaPhongBanChanged();
    partial void OnSoNhanVienChanging(int value);
    partial void OnSoNhanVienChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnKeyWordChanging(string value);
    partial void OnKeyWordChanged();
    #endregion
		
		public PHONGBAN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhongBan", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenPhongBan
		{
			get
			{
				return this._TenPhongBan;
			}
			set
			{
				if ((this._TenPhongBan != value))
				{
					this.OnTenPhongBanChanging(value);
					this.SendPropertyChanging();
					this._TenPhongBan = value;
					this.SendPropertyChanged("TenPhongBan");
					this.OnTenPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhongBan", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MaPhongBan
		{
			get
			{
				return this._MaPhongBan;
			}
			set
			{
				if ((this._MaPhongBan != value))
				{
					this.OnMaPhongBanChanging(value);
					this.SendPropertyChanging();
					this._MaPhongBan = value;
					this.SendPropertyChanged("MaPhongBan");
					this.OnMaPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNhanVien", DbType="Int NOT NULL")]
		public int SoNhanVien
		{
			get
			{
				return this._SoNhanVien;
			}
			set
			{
				if ((this._SoNhanVien != value))
				{
					this.OnSoNhanVienChanging(value);
					this.SendPropertyChanging();
					this._SoNhanVien = value;
					this.SendPropertyChanged("SoNhanVien");
					this.OnSoNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(255)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyWord", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string KeyWord
		{
			get
			{
				return this._KeyWord;
			}
			set
			{
				if ((this._KeyWord != value))
				{
					this.OnKeyWordChanging(value);
					this.SendPropertyChanging();
					this._KeyWord = value;
					this.SendPropertyChanged("KeyWord");
					this.OnKeyWordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QUYENHAN")]
	public partial class QUYENHAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TenQuyenHan;
		
		private string _MaQuyen;
		
		private string _GhiChu;
		
		private System.DateTime _NgayBatDau;
		
		private System.DateTime _NgayKetThuc;
		
		private string _KeyWord;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTenQuyenHanChanging(string value);
    partial void OnTenQuyenHanChanged();
    partial void OnMaQuyenChanging(string value);
    partial void OnMaQuyenChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnNgayBatDauChanging(System.DateTime value);
    partial void OnNgayBatDauChanged();
    partial void OnNgayKetThucChanging(System.DateTime value);
    partial void OnNgayKetThucChanged();
    partial void OnKeyWordChanging(string value);
    partial void OnKeyWordChanged();
    #endregion
		
		public QUYENHAN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQuyenHan", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenQuyenHan
		{
			get
			{
				return this._TenQuyenHan;
			}
			set
			{
				if ((this._TenQuyenHan != value))
				{
					this.OnTenQuyenHanChanging(value);
					this.SendPropertyChanging();
					this._TenQuyenHan = value;
					this.SendPropertyChanged("TenQuyenHan");
					this.OnTenQuyenHanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaQuyen", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MaQuyen
		{
			get
			{
				return this._MaQuyen;
			}
			set
			{
				if ((this._MaQuyen != value))
				{
					this.OnMaQuyenChanging(value);
					this.SendPropertyChanging();
					this._MaQuyen = value;
					this.SendPropertyChanged("MaQuyen");
					this.OnMaQuyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(255)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBatDau", DbType="Date NOT NULL")]
		public System.DateTime NgayBatDau
		{
			get
			{
				return this._NgayBatDau;
			}
			set
			{
				if ((this._NgayBatDau != value))
				{
					this.OnNgayBatDauChanging(value);
					this.SendPropertyChanging();
					this._NgayBatDau = value;
					this.SendPropertyChanged("NgayBatDau");
					this.OnNgayBatDauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKetThuc", DbType="Date NOT NULL")]
		public System.DateTime NgayKetThuc
		{
			get
			{
				return this._NgayKetThuc;
			}
			set
			{
				if ((this._NgayKetThuc != value))
				{
					this.OnNgayKetThucChanging(value);
					this.SendPropertyChanging();
					this._NgayKetThuc = value;
					this.SendPropertyChanged("NgayKetThuc");
					this.OnNgayKetThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyWord", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string KeyWord
		{
			get
			{
				return this._KeyWord;
			}
			set
			{
				if ((this._KeyWord != value))
				{
					this.OnKeyWordChanging(value);
					this.SendPropertyChanging();
					this._KeyWord = value;
					this.SendPropertyChanged("KeyWord");
					this.OnKeyWordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SOVANBAN")]
	public partial class SOVANBAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TenSoVanBan;
		
		private string _MaSoVanBan;
		
		private System.DateTime _NgayTaoSo;
		
		private System.DateTime _NgayDongSo;
		
		private string _KeyWord;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTenSoVanBanChanging(string value);
    partial void OnTenSoVanBanChanged();
    partial void OnMaSoVanBanChanging(string value);
    partial void OnMaSoVanBanChanged();
    partial void OnNgayTaoSoChanging(System.DateTime value);
    partial void OnNgayTaoSoChanged();
    partial void OnNgayDongSoChanging(System.DateTime value);
    partial void OnNgayDongSoChanged();
    partial void OnKeyWordChanging(string value);
    partial void OnKeyWordChanged();
    #endregion
		
		public SOVANBAN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSoVanBan", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TenSoVanBan
		{
			get
			{
				return this._TenSoVanBan;
			}
			set
			{
				if ((this._TenSoVanBan != value))
				{
					this.OnTenSoVanBanChanging(value);
					this.SendPropertyChanging();
					this._TenSoVanBan = value;
					this.SendPropertyChanged("TenSoVanBan");
					this.OnTenSoVanBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSoVanBan", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MaSoVanBan
		{
			get
			{
				return this._MaSoVanBan;
			}
			set
			{
				if ((this._MaSoVanBan != value))
				{
					this.OnMaSoVanBanChanging(value);
					this.SendPropertyChanging();
					this._MaSoVanBan = value;
					this.SendPropertyChanged("MaSoVanBan");
					this.OnMaSoVanBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayTaoSo", DbType="Date NOT NULL")]
		public System.DateTime NgayTaoSo
		{
			get
			{
				return this._NgayTaoSo;
			}
			set
			{
				if ((this._NgayTaoSo != value))
				{
					this.OnNgayTaoSoChanging(value);
					this.SendPropertyChanging();
					this._NgayTaoSo = value;
					this.SendPropertyChanged("NgayTaoSo");
					this.OnNgayTaoSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDongSo", DbType="Date NOT NULL")]
		public System.DateTime NgayDongSo
		{
			get
			{
				return this._NgayDongSo;
			}
			set
			{
				if ((this._NgayDongSo != value))
				{
					this.OnNgayDongSoChanging(value);
					this.SendPropertyChanging();
					this._NgayDongSo = value;
					this.SendPropertyChanged("NgayDongSo");
					this.OnNgayDongSoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyWord", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string KeyWord
		{
			get
			{
				return this._KeyWord;
			}
			set
			{
				if ((this._KeyWord != value))
				{
					this.OnKeyWordChanging(value);
					this.SendPropertyChanging();
					this._KeyWord = value;
					this.SendPropertyChanged("KeyWord");
					this.OnKeyWordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRANGTHAIVANBAN")]
	public partial class TRANGTHAIVANBAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _TenTrangThai;
		
		private string _MaTrangThai;
		
		private string _GhiChu;
		
		private string _KeyWord;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTenTrangThaiChanging(string value);
    partial void OnTenTrangThaiChanged();
    partial void OnMaTrangThaiChanging(string value);
    partial void OnMaTrangThaiChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnKeyWordChanging(string value);
    partial void OnKeyWordChanged();
    #endregion
		
		public TRANGTHAIVANBAN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTrangThai", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TenTrangThai
		{
			get
			{
				return this._TenTrangThai;
			}
			set
			{
				if ((this._TenTrangThai != value))
				{
					this.OnTenTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TenTrangThai = value;
					this.SendPropertyChanged("TenTrangThai");
					this.OnTenTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTrangThai", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MaTrangThai
		{
			get
			{
				return this._MaTrangThai;
			}
			set
			{
				if ((this._MaTrangThai != value))
				{
					this.OnMaTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._MaTrangThai = value;
					this.SendPropertyChanged("MaTrangThai");
					this.OnMaTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(255)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyWord", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string KeyWord
		{
			get
			{
				return this._KeyWord;
			}
			set
			{
				if ((this._KeyWord != value))
				{
					this.OnKeyWordChanging(value);
					this.SendPropertyChanging();
					this._KeyWord = value;
					this.SendPropertyChanged("KeyWord");
					this.OnKeyWordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.URLVANBANDEN")]
	public partial class URLVANBANDEN
	{
		
		private string _MaVanBan;
		
		private string _TenFile;
		
		private string _urlFile;
		
		public URLVANBANDEN()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVanBan", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaVanBan
		{
			get
			{
				return this._MaVanBan;
			}
			set
			{
				if ((this._MaVanBan != value))
				{
					this._MaVanBan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenFile", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string TenFile
		{
			get
			{
				return this._TenFile;
			}
			set
			{
				if ((this._TenFile != value))
				{
					this._TenFile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlFile", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string urlFile
		{
			get
			{
				return this._urlFile;
			}
			set
			{
				if ((this._urlFile != value))
				{
					this._urlFile = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VANBANDEN")]
	public partial class VANBANDEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _MaVanBan;
		
		private string _TrichYeu;
		
		private System.DateTime _NgayNhan;
		
		private System.DateTime _NgayBanHanhVanBan;
		
		private string _NoiLuuVanBan;
		
		private int _SoTo;
		
		private System.Nullable<System.DateTime> _NgayDuyetVanBan;
		
		private string _NguoiKyVanBan;
		
		private string _ChucVuNguoiKy;
		
		private string _DonViGui;
		
		private string _NoiDungVanBan;
		
		private string _urlNoiDungVanBan;
		
		private string _VanBanLienQuanVanBan;
		
		private string _urlVanBanLienQuanVanBan;
		
		private string _GhiChu;
		
		private int _NguoiDungId;
		
		private int _CongViecId;
		
		private int _LoaiVanBanId;
		
		private int _LuuTruId;
		
		private int _TrangThaiVanBanId;
		
		private int _QuyenId;
		
		private int _SoVanBanId;
		
		private string _KeyWord;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMaVanBanChanging(string value);
    partial void OnMaVanBanChanged();
    partial void OnTrichYeuChanging(string value);
    partial void OnTrichYeuChanged();
    partial void OnNgayNhanChanging(System.DateTime value);
    partial void OnNgayNhanChanged();
    partial void OnNgayBanHanhVanBanChanging(System.DateTime value);
    partial void OnNgayBanHanhVanBanChanged();
    partial void OnNoiLuuVanBanChanging(string value);
    partial void OnNoiLuuVanBanChanged();
    partial void OnSoToChanging(int value);
    partial void OnSoToChanged();
    partial void OnNgayDuyetVanBanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDuyetVanBanChanged();
    partial void OnNguoiKyVanBanChanging(string value);
    partial void OnNguoiKyVanBanChanged();
    partial void OnChucVuNguoiKyChanging(string value);
    partial void OnChucVuNguoiKyChanged();
    partial void OnDonViGuiChanging(string value);
    partial void OnDonViGuiChanged();
    partial void OnNoiDungVanBanChanging(string value);
    partial void OnNoiDungVanBanChanged();
    partial void OnurlNoiDungVanBanChanging(string value);
    partial void OnurlNoiDungVanBanChanged();
    partial void OnVanBanLienQuanVanBanChanging(string value);
    partial void OnVanBanLienQuanVanBanChanged();
    partial void OnurlVanBanLienQuanVanBanChanging(string value);
    partial void OnurlVanBanLienQuanVanBanChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    partial void OnNguoiDungIdChanging(int value);
    partial void OnNguoiDungIdChanged();
    partial void OnCongViecIdChanging(int value);
    partial void OnCongViecIdChanged();
    partial void OnLoaiVanBanIdChanging(int value);
    partial void OnLoaiVanBanIdChanged();
    partial void OnLuuTruIdChanging(int value);
    partial void OnLuuTruIdChanged();
    partial void OnTrangThaiVanBanIdChanging(int value);
    partial void OnTrangThaiVanBanIdChanged();
    partial void OnQuyenIdChanging(int value);
    partial void OnQuyenIdChanged();
    partial void OnSoVanBanIdChanging(int value);
    partial void OnSoVanBanIdChanged();
    partial void OnKeyWordChanging(string value);
    partial void OnKeyWordChanged();
    #endregion
		
		public VANBANDEN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaVanBan", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MaVanBan
		{
			get
			{
				return this._MaVanBan;
			}
			set
			{
				if ((this._MaVanBan != value))
				{
					this.OnMaVanBanChanging(value);
					this.SendPropertyChanging();
					this._MaVanBan = value;
					this.SendPropertyChanged("MaVanBan");
					this.OnMaVanBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrichYeu", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TrichYeu
		{
			get
			{
				return this._TrichYeu;
			}
			set
			{
				if ((this._TrichYeu != value))
				{
					this.OnTrichYeuChanging(value);
					this.SendPropertyChanging();
					this._TrichYeu = value;
					this.SendPropertyChanged("TrichYeu");
					this.OnTrichYeuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhan", DbType="DateTime NOT NULL")]
		public System.DateTime NgayNhan
		{
			get
			{
				return this._NgayNhan;
			}
			set
			{
				if ((this._NgayNhan != value))
				{
					this.OnNgayNhanChanging(value);
					this.SendPropertyChanging();
					this._NgayNhan = value;
					this.SendPropertyChanged("NgayNhan");
					this.OnNgayNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBanHanhVanBan", DbType="Date NOT NULL")]
		public System.DateTime NgayBanHanhVanBan
		{
			get
			{
				return this._NgayBanHanhVanBan;
			}
			set
			{
				if ((this._NgayBanHanhVanBan != value))
				{
					this.OnNgayBanHanhVanBanChanging(value);
					this.SendPropertyChanging();
					this._NgayBanHanhVanBan = value;
					this.SendPropertyChanged("NgayBanHanhVanBan");
					this.OnNgayBanHanhVanBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiLuuVanBan", DbType="NVarChar(255)")]
		public string NoiLuuVanBan
		{
			get
			{
				return this._NoiLuuVanBan;
			}
			set
			{
				if ((this._NoiLuuVanBan != value))
				{
					this.OnNoiLuuVanBanChanging(value);
					this.SendPropertyChanging();
					this._NoiLuuVanBan = value;
					this.SendPropertyChanged("NoiLuuVanBan");
					this.OnNoiLuuVanBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTo", DbType="Int NOT NULL")]
		public int SoTo
		{
			get
			{
				return this._SoTo;
			}
			set
			{
				if ((this._SoTo != value))
				{
					this.OnSoToChanging(value);
					this.SendPropertyChanging();
					this._SoTo = value;
					this.SendPropertyChanged("SoTo");
					this.OnSoToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDuyetVanBan", DbType="Date")]
		public System.Nullable<System.DateTime> NgayDuyetVanBan
		{
			get
			{
				return this._NgayDuyetVanBan;
			}
			set
			{
				if ((this._NgayDuyetVanBan != value))
				{
					this.OnNgayDuyetVanBanChanging(value);
					this.SendPropertyChanging();
					this._NgayDuyetVanBan = value;
					this.SendPropertyChanged("NgayDuyetVanBan");
					this.OnNgayDuyetVanBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiKyVanBan", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NguoiKyVanBan
		{
			get
			{
				return this._NguoiKyVanBan;
			}
			set
			{
				if ((this._NguoiKyVanBan != value))
				{
					this.OnNguoiKyVanBanChanging(value);
					this.SendPropertyChanging();
					this._NguoiKyVanBan = value;
					this.SendPropertyChanged("NguoiKyVanBan");
					this.OnNguoiKyVanBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVuNguoiKy", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string ChucVuNguoiKy
		{
			get
			{
				return this._ChucVuNguoiKy;
			}
			set
			{
				if ((this._ChucVuNguoiKy != value))
				{
					this.OnChucVuNguoiKyChanging(value);
					this.SendPropertyChanging();
					this._ChucVuNguoiKy = value;
					this.SendPropertyChanged("ChucVuNguoiKy");
					this.OnChucVuNguoiKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonViGui", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string DonViGui
		{
			get
			{
				return this._DonViGui;
			}
			set
			{
				if ((this._DonViGui != value))
				{
					this.OnDonViGuiChanging(value);
					this.SendPropertyChanging();
					this._DonViGui = value;
					this.SendPropertyChanged("DonViGui");
					this.OnDonViGuiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungVanBan", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string NoiDungVanBan
		{
			get
			{
				return this._NoiDungVanBan;
			}
			set
			{
				if ((this._NoiDungVanBan != value))
				{
					this.OnNoiDungVanBanChanging(value);
					this.SendPropertyChanging();
					this._NoiDungVanBan = value;
					this.SendPropertyChanged("NoiDungVanBan");
					this.OnNoiDungVanBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlNoiDungVanBan", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string urlNoiDungVanBan
		{
			get
			{
				return this._urlNoiDungVanBan;
			}
			set
			{
				if ((this._urlNoiDungVanBan != value))
				{
					this.OnurlNoiDungVanBanChanging(value);
					this.SendPropertyChanging();
					this._urlNoiDungVanBan = value;
					this.SendPropertyChanged("urlNoiDungVanBan");
					this.OnurlNoiDungVanBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VanBanLienQuanVanBan", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string VanBanLienQuanVanBan
		{
			get
			{
				return this._VanBanLienQuanVanBan;
			}
			set
			{
				if ((this._VanBanLienQuanVanBan != value))
				{
					this.OnVanBanLienQuanVanBanChanging(value);
					this.SendPropertyChanging();
					this._VanBanLienQuanVanBan = value;
					this.SendPropertyChanged("VanBanLienQuanVanBan");
					this.OnVanBanLienQuanVanBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urlVanBanLienQuanVanBan", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string urlVanBanLienQuanVanBan
		{
			get
			{
				return this._urlVanBanLienQuanVanBan;
			}
			set
			{
				if ((this._urlVanBanLienQuanVanBan != value))
				{
					this.OnurlVanBanLienQuanVanBanChanging(value);
					this.SendPropertyChanging();
					this._urlVanBanLienQuanVanBan = value;
					this.SendPropertyChanged("urlVanBanLienQuanVanBan");
					this.OnurlVanBanLienQuanVanBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(255)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NguoiDungId", DbType="Int NOT NULL")]
		public int NguoiDungId
		{
			get
			{
				return this._NguoiDungId;
			}
			set
			{
				if ((this._NguoiDungId != value))
				{
					this.OnNguoiDungIdChanging(value);
					this.SendPropertyChanging();
					this._NguoiDungId = value;
					this.SendPropertyChanged("NguoiDungId");
					this.OnNguoiDungIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CongViecId", DbType="Int NOT NULL")]
		public int CongViecId
		{
			get
			{
				return this._CongViecId;
			}
			set
			{
				if ((this._CongViecId != value))
				{
					this.OnCongViecIdChanging(value);
					this.SendPropertyChanging();
					this._CongViecId = value;
					this.SendPropertyChanged("CongViecId");
					this.OnCongViecIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiVanBanId", DbType="Int NOT NULL")]
		public int LoaiVanBanId
		{
			get
			{
				return this._LoaiVanBanId;
			}
			set
			{
				if ((this._LoaiVanBanId != value))
				{
					this.OnLoaiVanBanIdChanging(value);
					this.SendPropertyChanging();
					this._LoaiVanBanId = value;
					this.SendPropertyChanged("LoaiVanBanId");
					this.OnLoaiVanBanIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuuTruId", DbType="Int NOT NULL")]
		public int LuuTruId
		{
			get
			{
				return this._LuuTruId;
			}
			set
			{
				if ((this._LuuTruId != value))
				{
					this.OnLuuTruIdChanging(value);
					this.SendPropertyChanging();
					this._LuuTruId = value;
					this.SendPropertyChanged("LuuTruId");
					this.OnLuuTruIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiVanBanId", DbType="Int NOT NULL")]
		public int TrangThaiVanBanId
		{
			get
			{
				return this._TrangThaiVanBanId;
			}
			set
			{
				if ((this._TrangThaiVanBanId != value))
				{
					this.OnTrangThaiVanBanIdChanging(value);
					this.SendPropertyChanging();
					this._TrangThaiVanBanId = value;
					this.SendPropertyChanged("TrangThaiVanBanId");
					this.OnTrangThaiVanBanIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuyenId", DbType="Int NOT NULL")]
		public int QuyenId
		{
			get
			{
				return this._QuyenId;
			}
			set
			{
				if ((this._QuyenId != value))
				{
					this.OnQuyenIdChanging(value);
					this.SendPropertyChanging();
					this._QuyenId = value;
					this.SendPropertyChanged("QuyenId");
					this.OnQuyenIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoVanBanId", DbType="Int NOT NULL")]
		public int SoVanBanId
		{
			get
			{
				return this._SoVanBanId;
			}
			set
			{
				if ((this._SoVanBanId != value))
				{
					this.OnSoVanBanIdChanging(value);
					this.SendPropertyChanging();
					this._SoVanBanId = value;
					this.SendPropertyChanged("SoVanBanId");
					this.OnSoVanBanIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyWord", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string KeyWord
		{
			get
			{
				return this._KeyWord;
			}
			set
			{
				if ((this._KeyWord != value))
				{
					this.OnKeyWordChanging(value);
					this.SendPropertyChanging();
					this._KeyWord = value;
					this.SendPropertyChanged("KeyWord");
					this.OnKeyWordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
