#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Do_An_CNPM.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="websiteDB")]
	public partial class DataWebsiteDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertVANBANNOIBO(VANBANNOIBO instance);
    partial void UpdateVANBANNOIBO(VANBANNOIBO instance);
    partial void DeleteVANBANNOIBO(VANBANNOIBO instance);
    partial void InsertDOITAC(DOITAC instance);
    partial void UpdateDOITAC(DOITAC instance);
    partial void DeleteDOITAC(DOITAC instance);
    partial void InsertLOAIVANBAN(LOAIVANBAN instance);
    partial void UpdateLOAIVANBAN(LOAIVANBAN instance);
    partial void DeleteLOAIVANBAN(LOAIVANBAN instance);
    partial void InsertNGUOIDUNG(NGUOIDUNG instance);
    partial void UpdateNGUOIDUNG(NGUOIDUNG instance);
    partial void DeleteNGUOIDUNG(NGUOIDUNG instance);
    partial void InsertPHONGBAN(PHONGBAN instance);
    partial void UpdatePHONGBAN(PHONGBAN instance);
    partial void DeletePHONGBAN(PHONGBAN instance);
    partial void InsertQUYENHAN(QUYENHAN instance);
    partial void UpdateQUYENHAN(QUYENHAN instance);
    partial void DeleteQUYENHAN(QUYENHAN instance);
    partial void InsertTRANGTHAIVANBAN(TRANGTHAIVANBAN instance);
    partial void UpdateTRANGTHAIVANBAN(TRANGTHAIVANBAN instance);
    partial void DeleteTRANGTHAIVANBAN(TRANGTHAIVANBAN instance);
    partial void InsertVANBANDEN(VANBANDEN instance);
    partial void UpdateVANBANDEN(VANBANDEN instance);
    partial void DeleteVANBANDEN(VANBANDEN instance);
    partial void InsertVANBANDI(VANBANDI instance);
    partial void UpdateVANBANDI(VANBANDI instance);
    partial void DeleteVANBANDI(VANBANDI instance);
    #endregion
		
		public DataWebsiteDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataWebsiteDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataWebsiteDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataWebsiteDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<VANBANNOIBO> VANBANNOIBOs
		{
			get
			{
				return this.GetTable<VANBANNOIBO>();
			}
		}
		
		public System.Data.Linq.Table<DOITAC> DOITACs
		{
			get
			{
				return this.GetTable<DOITAC>();
			}
		}
		
		public System.Data.Linq.Table<LOAIVANBAN> LOAIVANBANs
		{
			get
			{
				return this.GetTable<LOAIVANBAN>();
			}
		}
		
		public System.Data.Linq.Table<NGUOIDUNG> NGUOIDUNGs
		{
			get
			{
				return this.GetTable<NGUOIDUNG>();
			}
		}
		
		public System.Data.Linq.Table<PHONGBAN> PHONGBANs
		{
			get
			{
				return this.GetTable<PHONGBAN>();
			}
		}
		
		public System.Data.Linq.Table<QUYENHAN> QUYENHANs
		{
			get
			{
				return this.GetTable<QUYENHAN>();
			}
		}
		
		public System.Data.Linq.Table<TRANGTHAIVANBAN> TRANGTHAIVANBANs
		{
			get
			{
				return this.GetTable<TRANGTHAIVANBAN>();
			}
		}
		
		public System.Data.Linq.Table<VANBANDEN> VANBANDENs
		{
			get
			{
				return this.GetTable<VANBANDEN>();
			}
		}
		
		public System.Data.Linq.Table<VANBANDI> VANBANDIs
		{
			get
			{
				return this.GetTable<VANBANDI>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VANBANNOIBO")]
	public partial class VANBANNOIBO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_VanBanNoiBo;
		
		private string _TenVanBanNoiBo;
		
		private string _TrichYeuVanBanNoiBo;
		
		private string _SoHieuGocVanBanNoiBo;
		
		private System.DateTime _NgayVanBanNoiBo;
		
		private System.DateTime _NgayBanHanhVanBanNoiBo;
		
		private string _NoiLuuVanBanNoiBo;
		
		private string _SoBanPhatHanhVanBanNoiBo;
		
		private System.DateTime _NgayDuyetVanBanNoiBo;
		
		private System.DateTime _NgayLuuSoVanBanNoiBo;
		
		private string _NoiDungVanBanNoiBo;
		
		private string _VanBanLienQuanVanBanNoiBo;
		
		private int _ID_VANBANNOIBO_NGUOIDUNG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_VanBanNoiBoChanging(int value);
    partial void OnID_VanBanNoiBoChanged();
    partial void OnTenVanBanNoiBoChanging(string value);
    partial void OnTenVanBanNoiBoChanged();
    partial void OnTrichYeuVanBanNoiBoChanging(string value);
    partial void OnTrichYeuVanBanNoiBoChanged();
    partial void OnSoHieuGocVanBanNoiBoChanging(string value);
    partial void OnSoHieuGocVanBanNoiBoChanged();
    partial void OnNgayVanBanNoiBoChanging(System.DateTime value);
    partial void OnNgayVanBanNoiBoChanged();
    partial void OnNgayBanHanhVanBanNoiBoChanging(System.DateTime value);
    partial void OnNgayBanHanhVanBanNoiBoChanged();
    partial void OnNoiLuuVanBanNoiBoChanging(string value);
    partial void OnNoiLuuVanBanNoiBoChanged();
    partial void OnSoBanPhatHanhVanBanNoiBoChanging(string value);
    partial void OnSoBanPhatHanhVanBanNoiBoChanged();
    partial void OnNgayDuyetVanBanNoiBoChanging(System.DateTime value);
    partial void OnNgayDuyetVanBanNoiBoChanged();
    partial void OnNgayLuuSoVanBanNoiBoChanging(System.DateTime value);
    partial void OnNgayLuuSoVanBanNoiBoChanged();
    partial void OnNoiDungVanBanNoiBoChanging(string value);
    partial void OnNoiDungVanBanNoiBoChanged();
    partial void OnVanBanLienQuanVanBanNoiBoChanging(string value);
    partial void OnVanBanLienQuanVanBanNoiBoChanged();
    partial void OnID_VANBANNOIBO_NGUOIDUNGChanging(int value);
    partial void OnID_VANBANNOIBO_NGUOIDUNGChanged();
    #endregion
		
		public VANBANNOIBO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_VanBanNoiBo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_VanBanNoiBo
		{
			get
			{
				return this._ID_VanBanNoiBo;
			}
			set
			{
				if ((this._ID_VanBanNoiBo != value))
				{
					this.OnID_VanBanNoiBoChanging(value);
					this.SendPropertyChanging();
					this._ID_VanBanNoiBo = value;
					this.SendPropertyChanged("ID_VanBanNoiBo");
					this.OnID_VanBanNoiBoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenVanBanNoiBo", DbType="NChar(255) NOT NULL", CanBeNull=false)]
		public string TenVanBanNoiBo
		{
			get
			{
				return this._TenVanBanNoiBo;
			}
			set
			{
				if ((this._TenVanBanNoiBo != value))
				{
					this.OnTenVanBanNoiBoChanging(value);
					this.SendPropertyChanging();
					this._TenVanBanNoiBo = value;
					this.SendPropertyChanged("TenVanBanNoiBo");
					this.OnTenVanBanNoiBoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrichYeuVanBanNoiBo", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string TrichYeuVanBanNoiBo
		{
			get
			{
				return this._TrichYeuVanBanNoiBo;
			}
			set
			{
				if ((this._TrichYeuVanBanNoiBo != value))
				{
					this.OnTrichYeuVanBanNoiBoChanging(value);
					this.SendPropertyChanging();
					this._TrichYeuVanBanNoiBo = value;
					this.SendPropertyChanged("TrichYeuVanBanNoiBo");
					this.OnTrichYeuVanBanNoiBoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoHieuGocVanBanNoiBo", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string SoHieuGocVanBanNoiBo
		{
			get
			{
				return this._SoHieuGocVanBanNoiBo;
			}
			set
			{
				if ((this._SoHieuGocVanBanNoiBo != value))
				{
					this.OnSoHieuGocVanBanNoiBoChanging(value);
					this.SendPropertyChanging();
					this._SoHieuGocVanBanNoiBo = value;
					this.SendPropertyChanged("SoHieuGocVanBanNoiBo");
					this.OnSoHieuGocVanBanNoiBoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayVanBanNoiBo", DbType="DateTime NOT NULL")]
		public System.DateTime NgayVanBanNoiBo
		{
			get
			{
				return this._NgayVanBanNoiBo;
			}
			set
			{
				if ((this._NgayVanBanNoiBo != value))
				{
					this.OnNgayVanBanNoiBoChanging(value);
					this.SendPropertyChanging();
					this._NgayVanBanNoiBo = value;
					this.SendPropertyChanged("NgayVanBanNoiBo");
					this.OnNgayVanBanNoiBoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBanHanhVanBanNoiBo", DbType="Date NOT NULL")]
		public System.DateTime NgayBanHanhVanBanNoiBo
		{
			get
			{
				return this._NgayBanHanhVanBanNoiBo;
			}
			set
			{
				if ((this._NgayBanHanhVanBanNoiBo != value))
				{
					this.OnNgayBanHanhVanBanNoiBoChanging(value);
					this.SendPropertyChanging();
					this._NgayBanHanhVanBanNoiBo = value;
					this.SendPropertyChanged("NgayBanHanhVanBanNoiBo");
					this.OnNgayBanHanhVanBanNoiBoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiLuuVanBanNoiBo", DbType="NVarChar(255)")]
		public string NoiLuuVanBanNoiBo
		{
			get
			{
				return this._NoiLuuVanBanNoiBo;
			}
			set
			{
				if ((this._NoiLuuVanBanNoiBo != value))
				{
					this.OnNoiLuuVanBanNoiBoChanging(value);
					this.SendPropertyChanging();
					this._NoiLuuVanBanNoiBo = value;
					this.SendPropertyChanged("NoiLuuVanBanNoiBo");
					this.OnNoiLuuVanBanNoiBoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBanPhatHanhVanBanNoiBo", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string SoBanPhatHanhVanBanNoiBo
		{
			get
			{
				return this._SoBanPhatHanhVanBanNoiBo;
			}
			set
			{
				if ((this._SoBanPhatHanhVanBanNoiBo != value))
				{
					this.OnSoBanPhatHanhVanBanNoiBoChanging(value);
					this.SendPropertyChanging();
					this._SoBanPhatHanhVanBanNoiBo = value;
					this.SendPropertyChanged("SoBanPhatHanhVanBanNoiBo");
					this.OnSoBanPhatHanhVanBanNoiBoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDuyetVanBanNoiBo", DbType="DateTime NOT NULL")]
		public System.DateTime NgayDuyetVanBanNoiBo
		{
			get
			{
				return this._NgayDuyetVanBanNoiBo;
			}
			set
			{
				if ((this._NgayDuyetVanBanNoiBo != value))
				{
					this.OnNgayDuyetVanBanNoiBoChanging(value);
					this.SendPropertyChanging();
					this._NgayDuyetVanBanNoiBo = value;
					this.SendPropertyChanged("NgayDuyetVanBanNoiBo");
					this.OnNgayDuyetVanBanNoiBoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLuuSoVanBanNoiBo", DbType="DateTime NOT NULL")]
		public System.DateTime NgayLuuSoVanBanNoiBo
		{
			get
			{
				return this._NgayLuuSoVanBanNoiBo;
			}
			set
			{
				if ((this._NgayLuuSoVanBanNoiBo != value))
				{
					this.OnNgayLuuSoVanBanNoiBoChanging(value);
					this.SendPropertyChanging();
					this._NgayLuuSoVanBanNoiBo = value;
					this.SendPropertyChanged("NgayLuuSoVanBanNoiBo");
					this.OnNgayLuuSoVanBanNoiBoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungVanBanNoiBo", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string NoiDungVanBanNoiBo
		{
			get
			{
				return this._NoiDungVanBanNoiBo;
			}
			set
			{
				if ((this._NoiDungVanBanNoiBo != value))
				{
					this.OnNoiDungVanBanNoiBoChanging(value);
					this.SendPropertyChanging();
					this._NoiDungVanBanNoiBo = value;
					this.SendPropertyChanged("NoiDungVanBanNoiBo");
					this.OnNoiDungVanBanNoiBoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VanBanLienQuanVanBanNoiBo", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string VanBanLienQuanVanBanNoiBo
		{
			get
			{
				return this._VanBanLienQuanVanBanNoiBo;
			}
			set
			{
				if ((this._VanBanLienQuanVanBanNoiBo != value))
				{
					this.OnVanBanLienQuanVanBanNoiBoChanging(value);
					this.SendPropertyChanging();
					this._VanBanLienQuanVanBanNoiBo = value;
					this.SendPropertyChanged("VanBanLienQuanVanBanNoiBo");
					this.OnVanBanLienQuanVanBanNoiBoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_VANBANNOIBO_NGUOIDUNG", DbType="Int NOT NULL")]
		public int ID_VANBANNOIBO_NGUOIDUNG
		{
			get
			{
				return this._ID_VANBANNOIBO_NGUOIDUNG;
			}
			set
			{
				if ((this._ID_VANBANNOIBO_NGUOIDUNG != value))
				{
					this.OnID_VANBANNOIBO_NGUOIDUNGChanging(value);
					this.SendPropertyChanging();
					this._ID_VANBANNOIBO_NGUOIDUNG = value;
					this.SendPropertyChanged("ID_VANBANNOIBO_NGUOIDUNG");
					this.OnID_VANBANNOIBO_NGUOIDUNGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DOITAC")]
	public partial class DOITAC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_DOITAC;
		
		private string _TenDoiTac;
		
		private string _PhanLoai;
		
		private int _ID_DOITAC_VANBANDEN;
		
		private int _ID_DOITAC_TRANGTHAIVANBAN;
		
		private int _ID_DOITAC_VANBANDI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_DOITACChanging(int value);
    partial void OnID_DOITACChanged();
    partial void OnTenDoiTacChanging(string value);
    partial void OnTenDoiTacChanged();
    partial void OnPhanLoaiChanging(string value);
    partial void OnPhanLoaiChanged();
    partial void OnID_DOITAC_VANBANDENChanging(int value);
    partial void OnID_DOITAC_VANBANDENChanged();
    partial void OnID_DOITAC_TRANGTHAIVANBANChanging(int value);
    partial void OnID_DOITAC_TRANGTHAIVANBANChanged();
    partial void OnID_DOITAC_VANBANDIChanging(int value);
    partial void OnID_DOITAC_VANBANDIChanged();
    #endregion
		
		public DOITAC()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DOITAC", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_DOITAC
		{
			get
			{
				return this._ID_DOITAC;
			}
			set
			{
				if ((this._ID_DOITAC != value))
				{
					this.OnID_DOITACChanging(value);
					this.SendPropertyChanging();
					this._ID_DOITAC = value;
					this.SendPropertyChanged("ID_DOITAC");
					this.OnID_DOITACChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDoiTac", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string TenDoiTac
		{
			get
			{
				return this._TenDoiTac;
			}
			set
			{
				if ((this._TenDoiTac != value))
				{
					this.OnTenDoiTacChanging(value);
					this.SendPropertyChanging();
					this._TenDoiTac = value;
					this.SendPropertyChanged("TenDoiTac");
					this.OnTenDoiTacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhanLoai", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string PhanLoai
		{
			get
			{
				return this._PhanLoai;
			}
			set
			{
				if ((this._PhanLoai != value))
				{
					this.OnPhanLoaiChanging(value);
					this.SendPropertyChanging();
					this._PhanLoai = value;
					this.SendPropertyChanged("PhanLoai");
					this.OnPhanLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DOITAC_VANBANDEN", DbType="Int NOT NULL")]
		public int ID_DOITAC_VANBANDEN
		{
			get
			{
				return this._ID_DOITAC_VANBANDEN;
			}
			set
			{
				if ((this._ID_DOITAC_VANBANDEN != value))
				{
					this.OnID_DOITAC_VANBANDENChanging(value);
					this.SendPropertyChanging();
					this._ID_DOITAC_VANBANDEN = value;
					this.SendPropertyChanged("ID_DOITAC_VANBANDEN");
					this.OnID_DOITAC_VANBANDENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DOITAC_TRANGTHAIVANBAN", DbType="Int NOT NULL")]
		public int ID_DOITAC_TRANGTHAIVANBAN
		{
			get
			{
				return this._ID_DOITAC_TRANGTHAIVANBAN;
			}
			set
			{
				if ((this._ID_DOITAC_TRANGTHAIVANBAN != value))
				{
					this.OnID_DOITAC_TRANGTHAIVANBANChanging(value);
					this.SendPropertyChanging();
					this._ID_DOITAC_TRANGTHAIVANBAN = value;
					this.SendPropertyChanged("ID_DOITAC_TRANGTHAIVANBAN");
					this.OnID_DOITAC_TRANGTHAIVANBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DOITAC_VANBANDI", DbType="Int NOT NULL")]
		public int ID_DOITAC_VANBANDI
		{
			get
			{
				return this._ID_DOITAC_VANBANDI;
			}
			set
			{
				if ((this._ID_DOITAC_VANBANDI != value))
				{
					this.OnID_DOITAC_VANBANDIChanging(value);
					this.SendPropertyChanging();
					this._ID_DOITAC_VANBANDI = value;
					this.SendPropertyChanged("ID_DOITAC_VANBANDI");
					this.OnID_DOITAC_VANBANDIChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIVANBAN")]
	public partial class LOAIVANBAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_LOAIVANBAN;
		
		private string _TenLoaiVanBan;
		
		private string _LinhVucVanBan;
		
		private int _CapDo;
		
		private int _ID_LOAIVANBAN_VANBANDEN;
		
		private int _ID_LOAIVANBAN_VANBANDI;
		
		private int _ID_LOAIVANBAN_VANBANNOIBO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_LOAIVANBANChanging(int value);
    partial void OnID_LOAIVANBANChanged();
    partial void OnTenLoaiVanBanChanging(string value);
    partial void OnTenLoaiVanBanChanged();
    partial void OnLinhVucVanBanChanging(string value);
    partial void OnLinhVucVanBanChanged();
    partial void OnCapDoChanging(int value);
    partial void OnCapDoChanged();
    partial void OnID_LOAIVANBAN_VANBANDENChanging(int value);
    partial void OnID_LOAIVANBAN_VANBANDENChanged();
    partial void OnID_LOAIVANBAN_VANBANDIChanging(int value);
    partial void OnID_LOAIVANBAN_VANBANDIChanged();
    partial void OnID_LOAIVANBAN_VANBANNOIBOChanging(int value);
    partial void OnID_LOAIVANBAN_VANBANNOIBOChanged();
    #endregion
		
		public LOAIVANBAN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOAIVANBAN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_LOAIVANBAN
		{
			get
			{
				return this._ID_LOAIVANBAN;
			}
			set
			{
				if ((this._ID_LOAIVANBAN != value))
				{
					this.OnID_LOAIVANBANChanging(value);
					this.SendPropertyChanging();
					this._ID_LOAIVANBAN = value;
					this.SendPropertyChanged("ID_LOAIVANBAN");
					this.OnID_LOAIVANBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiVanBan", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string TenLoaiVanBan
		{
			get
			{
				return this._TenLoaiVanBan;
			}
			set
			{
				if ((this._TenLoaiVanBan != value))
				{
					this.OnTenLoaiVanBanChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiVanBan = value;
					this.SendPropertyChanged("TenLoaiVanBan");
					this.OnTenLoaiVanBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinhVucVanBan", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string LinhVucVanBan
		{
			get
			{
				return this._LinhVucVanBan;
			}
			set
			{
				if ((this._LinhVucVanBan != value))
				{
					this.OnLinhVucVanBanChanging(value);
					this.SendPropertyChanging();
					this._LinhVucVanBan = value;
					this.SendPropertyChanged("LinhVucVanBan");
					this.OnLinhVucVanBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CapDo", DbType="Int NOT NULL")]
		public int CapDo
		{
			get
			{
				return this._CapDo;
			}
			set
			{
				if ((this._CapDo != value))
				{
					this.OnCapDoChanging(value);
					this.SendPropertyChanging();
					this._CapDo = value;
					this.SendPropertyChanged("CapDo");
					this.OnCapDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOAIVANBAN_VANBANDEN", DbType="Int NOT NULL")]
		public int ID_LOAIVANBAN_VANBANDEN
		{
			get
			{
				return this._ID_LOAIVANBAN_VANBANDEN;
			}
			set
			{
				if ((this._ID_LOAIVANBAN_VANBANDEN != value))
				{
					this.OnID_LOAIVANBAN_VANBANDENChanging(value);
					this.SendPropertyChanging();
					this._ID_LOAIVANBAN_VANBANDEN = value;
					this.SendPropertyChanged("ID_LOAIVANBAN_VANBANDEN");
					this.OnID_LOAIVANBAN_VANBANDENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOAIVANBAN_VANBANDI", DbType="Int NOT NULL")]
		public int ID_LOAIVANBAN_VANBANDI
		{
			get
			{
				return this._ID_LOAIVANBAN_VANBANDI;
			}
			set
			{
				if ((this._ID_LOAIVANBAN_VANBANDI != value))
				{
					this.OnID_LOAIVANBAN_VANBANDIChanging(value);
					this.SendPropertyChanging();
					this._ID_LOAIVANBAN_VANBANDI = value;
					this.SendPropertyChanged("ID_LOAIVANBAN_VANBANDI");
					this.OnID_LOAIVANBAN_VANBANDIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LOAIVANBAN_VANBANNOIBO", DbType="Int NOT NULL")]
		public int ID_LOAIVANBAN_VANBANNOIBO
		{
			get
			{
				return this._ID_LOAIVANBAN_VANBANNOIBO;
			}
			set
			{
				if ((this._ID_LOAIVANBAN_VANBANNOIBO != value))
				{
					this.OnID_LOAIVANBAN_VANBANNOIBOChanging(value);
					this.SendPropertyChanging();
					this._ID_LOAIVANBAN_VANBANNOIBO = value;
					this.SendPropertyChanged("ID_LOAIVANBAN_VANBANNOIBO");
					this.OnID_LOAIVANBAN_VANBANNOIBOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NGUOIDUNG")]
	public partial class NGUOIDUNG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_NGUOIDUNG;
		
		private string _MaNhanVien;
		
		private string _MatKhau;
		
		private string _TenNguoiDung;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _ChucVu;
		
		private string _QueQuan;
		
		private string _Mail;
		
		private string _SoDienThoai;
		
		private int _ID_NGUOIDUNG_LOAIVANBAN;
		
		private int _ID_NGUOIDUNG_PHONGBAN;
		
		private int _ID_NGUOIDUNG_QUYENHAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_NGUOIDUNGChanging(int value);
    partial void OnID_NGUOIDUNGChanged();
    partial void OnMaNhanVienChanging(string value);
    partial void OnMaNhanVienChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnTenNguoiDungChanging(string value);
    partial void OnTenNguoiDungChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnChucVuChanging(string value);
    partial void OnChucVuChanged();
    partial void OnQueQuanChanging(string value);
    partial void OnQueQuanChanged();
    partial void OnMailChanging(string value);
    partial void OnMailChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnID_NGUOIDUNG_LOAIVANBANChanging(int value);
    partial void OnID_NGUOIDUNG_LOAIVANBANChanged();
    partial void OnID_NGUOIDUNG_PHONGBANChanging(int value);
    partial void OnID_NGUOIDUNG_PHONGBANChanged();
    partial void OnID_NGUOIDUNG_QUYENHANChanging(int value);
    partial void OnID_NGUOIDUNG_QUYENHANChanged();
    #endregion
		
		public NGUOIDUNG()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NGUOIDUNG", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_NGUOIDUNG
		{
			get
			{
				return this._ID_NGUOIDUNG;
			}
			set
			{
				if ((this._ID_NGUOIDUNG != value))
				{
					this.OnID_NGUOIDUNGChanging(value);
					this.SendPropertyChanging();
					this._ID_NGUOIDUNG = value;
					this.SendPropertyChanged("ID_NGUOIDUNG");
					this.OnID_NGUOIDUNGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhanVien", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MaNhanVien
		{
			get
			{
				return this._MaNhanVien;
			}
			set
			{
				if ((this._MaNhanVien != value))
				{
					this.OnMaNhanVienChanging(value);
					this.SendPropertyChanging();
					this._MaNhanVien = value;
					this.SendPropertyChanged("MaNhanVien");
					this.OnMaNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNguoiDung", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string TenNguoiDung
		{
			get
			{
				return this._TenNguoiDung;
			}
			set
			{
				if ((this._TenNguoiDung != value))
				{
					this.OnTenNguoiDungChanging(value);
					this.SendPropertyChanging();
					this._TenNguoiDung = value;
					this.SendPropertyChanged("TenNguoiDung");
					this.OnTenNguoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChucVu", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string ChucVu
		{
			get
			{
				return this._ChucVu;
			}
			set
			{
				if ((this._ChucVu != value))
				{
					this.OnChucVuChanging(value);
					this.SendPropertyChanging();
					this._ChucVu = value;
					this.SendPropertyChanged("ChucVu");
					this.OnChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QueQuan", DbType="NChar(100)")]
		public string QueQuan
		{
			get
			{
				return this._QueQuan;
			}
			set
			{
				if ((this._QueQuan != value))
				{
					this.OnQueQuanChanging(value);
					this.SendPropertyChanging();
					this._QueQuan = value;
					this.SendPropertyChanged("QueQuan");
					this.OnQueQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mail", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string Mail
		{
			get
			{
				return this._Mail;
			}
			set
			{
				if ((this._Mail != value))
				{
					this.OnMailChanging(value);
					this.SendPropertyChanging();
					this._Mail = value;
					this.SendPropertyChanged("Mail");
					this.OnMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NGUOIDUNG_LOAIVANBAN", DbType="Int NOT NULL")]
		public int ID_NGUOIDUNG_LOAIVANBAN
		{
			get
			{
				return this._ID_NGUOIDUNG_LOAIVANBAN;
			}
			set
			{
				if ((this._ID_NGUOIDUNG_LOAIVANBAN != value))
				{
					this.OnID_NGUOIDUNG_LOAIVANBANChanging(value);
					this.SendPropertyChanging();
					this._ID_NGUOIDUNG_LOAIVANBAN = value;
					this.SendPropertyChanged("ID_NGUOIDUNG_LOAIVANBAN");
					this.OnID_NGUOIDUNG_LOAIVANBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NGUOIDUNG_PHONGBAN", DbType="Int NOT NULL")]
		public int ID_NGUOIDUNG_PHONGBAN
		{
			get
			{
				return this._ID_NGUOIDUNG_PHONGBAN;
			}
			set
			{
				if ((this._ID_NGUOIDUNG_PHONGBAN != value))
				{
					this.OnID_NGUOIDUNG_PHONGBANChanging(value);
					this.SendPropertyChanging();
					this._ID_NGUOIDUNG_PHONGBAN = value;
					this.SendPropertyChanged("ID_NGUOIDUNG_PHONGBAN");
					this.OnID_NGUOIDUNG_PHONGBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_NGUOIDUNG_QUYENHAN", DbType="Int NOT NULL")]
		public int ID_NGUOIDUNG_QUYENHAN
		{
			get
			{
				return this._ID_NGUOIDUNG_QUYENHAN;
			}
			set
			{
				if ((this._ID_NGUOIDUNG_QUYENHAN != value))
				{
					this.OnID_NGUOIDUNG_QUYENHANChanging(value);
					this.SendPropertyChanging();
					this._ID_NGUOIDUNG_QUYENHAN = value;
					this.SendPropertyChanged("ID_NGUOIDUNG_QUYENHAN");
					this.OnID_NGUOIDUNG_QUYENHANChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHONGBAN")]
	public partial class PHONGBAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_PHONGBAN;
		
		private string _TenPhongBan;
		
		private int _SoNhanVien;
		
		private int _ID_PHONGBAN_QUYENHAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_PHONGBANChanging(int value);
    partial void OnID_PHONGBANChanged();
    partial void OnTenPhongBanChanging(string value);
    partial void OnTenPhongBanChanged();
    partial void OnSoNhanVienChanging(int value);
    partial void OnSoNhanVienChanged();
    partial void OnID_PHONGBAN_QUYENHANChanging(int value);
    partial void OnID_PHONGBAN_QUYENHANChanged();
    #endregion
		
		public PHONGBAN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PHONGBAN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_PHONGBAN
		{
			get
			{
				return this._ID_PHONGBAN;
			}
			set
			{
				if ((this._ID_PHONGBAN != value))
				{
					this.OnID_PHONGBANChanging(value);
					this.SendPropertyChanging();
					this._ID_PHONGBAN = value;
					this.SendPropertyChanged("ID_PHONGBAN");
					this.OnID_PHONGBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhongBan", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string TenPhongBan
		{
			get
			{
				return this._TenPhongBan;
			}
			set
			{
				if ((this._TenPhongBan != value))
				{
					this.OnTenPhongBanChanging(value);
					this.SendPropertyChanging();
					this._TenPhongBan = value;
					this.SendPropertyChanged("TenPhongBan");
					this.OnTenPhongBanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoNhanVien", DbType="Int NOT NULL")]
		public int SoNhanVien
		{
			get
			{
				return this._SoNhanVien;
			}
			set
			{
				if ((this._SoNhanVien != value))
				{
					this.OnSoNhanVienChanging(value);
					this.SendPropertyChanging();
					this._SoNhanVien = value;
					this.SendPropertyChanged("SoNhanVien");
					this.OnSoNhanVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_PHONGBAN_QUYENHAN", DbType="Int NOT NULL")]
		public int ID_PHONGBAN_QUYENHAN
		{
			get
			{
				return this._ID_PHONGBAN_QUYENHAN;
			}
			set
			{
				if ((this._ID_PHONGBAN_QUYENHAN != value))
				{
					this.OnID_PHONGBAN_QUYENHANChanging(value);
					this.SendPropertyChanging();
					this._ID_PHONGBAN_QUYENHAN = value;
					this.SendPropertyChanged("ID_PHONGBAN_QUYENHAN");
					this.OnID_PHONGBAN_QUYENHANChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QUYENHAN")]
	public partial class QUYENHAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_QUYENHAN;
		
		private string _TenQuyenHan;
		
		private int _ID_QUYENHAN_NGUOIDUNG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_QUYENHANChanging(int value);
    partial void OnID_QUYENHANChanged();
    partial void OnTenQuyenHanChanging(string value);
    partial void OnTenQuyenHanChanged();
    partial void OnID_QUYENHAN_NGUOIDUNGChanging(int value);
    partial void OnID_QUYENHAN_NGUOIDUNGChanged();
    #endregion
		
		public QUYENHAN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_QUYENHAN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_QUYENHAN
		{
			get
			{
				return this._ID_QUYENHAN;
			}
			set
			{
				if ((this._ID_QUYENHAN != value))
				{
					this.OnID_QUYENHANChanging(value);
					this.SendPropertyChanging();
					this._ID_QUYENHAN = value;
					this.SendPropertyChanged("ID_QUYENHAN");
					this.OnID_QUYENHANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQuyenHan", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string TenQuyenHan
		{
			get
			{
				return this._TenQuyenHan;
			}
			set
			{
				if ((this._TenQuyenHan != value))
				{
					this.OnTenQuyenHanChanging(value);
					this.SendPropertyChanging();
					this._TenQuyenHan = value;
					this.SendPropertyChanged("TenQuyenHan");
					this.OnTenQuyenHanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_QUYENHAN_NGUOIDUNG", DbType="Int NOT NULL")]
		public int ID_QUYENHAN_NGUOIDUNG
		{
			get
			{
				return this._ID_QUYENHAN_NGUOIDUNG;
			}
			set
			{
				if ((this._ID_QUYENHAN_NGUOIDUNG != value))
				{
					this.OnID_QUYENHAN_NGUOIDUNGChanging(value);
					this.SendPropertyChanging();
					this._ID_QUYENHAN_NGUOIDUNG = value;
					this.SendPropertyChanged("ID_QUYENHAN_NGUOIDUNG");
					this.OnID_QUYENHAN_NGUOIDUNGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRANGTHAIVANBAN")]
	public partial class TRANGTHAIVANBAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_TRANGTHAIVANBAN;
		
		private string _TenTrangThai;
		
		private int _ID_TRANGTHAIVANBAN_VANBANDEN;
		
		private int _ID_TRANGTHAIVANBAN_VANBANDI;
		
		private int _ID_TRANGTHAIVANBAN_VANBANNOIBO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_TRANGTHAIVANBANChanging(int value);
    partial void OnID_TRANGTHAIVANBANChanged();
    partial void OnTenTrangThaiChanging(string value);
    partial void OnTenTrangThaiChanged();
    partial void OnID_TRANGTHAIVANBAN_VANBANDENChanging(int value);
    partial void OnID_TRANGTHAIVANBAN_VANBANDENChanged();
    partial void OnID_TRANGTHAIVANBAN_VANBANDIChanging(int value);
    partial void OnID_TRANGTHAIVANBAN_VANBANDIChanged();
    partial void OnID_TRANGTHAIVANBAN_VANBANNOIBOChanging(int value);
    partial void OnID_TRANGTHAIVANBAN_VANBANNOIBOChanged();
    #endregion
		
		public TRANGTHAIVANBAN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TRANGTHAIVANBAN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_TRANGTHAIVANBAN
		{
			get
			{
				return this._ID_TRANGTHAIVANBAN;
			}
			set
			{
				if ((this._ID_TRANGTHAIVANBAN != value))
				{
					this.OnID_TRANGTHAIVANBANChanging(value);
					this.SendPropertyChanging();
					this._ID_TRANGTHAIVANBAN = value;
					this.SendPropertyChanged("ID_TRANGTHAIVANBAN");
					this.OnID_TRANGTHAIVANBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTrangThai", DbType="NChar(50) NOT NULL", CanBeNull=false)]
		public string TenTrangThai
		{
			get
			{
				return this._TenTrangThai;
			}
			set
			{
				if ((this._TenTrangThai != value))
				{
					this.OnTenTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TenTrangThai = value;
					this.SendPropertyChanged("TenTrangThai");
					this.OnTenTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TRANGTHAIVANBAN_VANBANDEN", DbType="Int NOT NULL")]
		public int ID_TRANGTHAIVANBAN_VANBANDEN
		{
			get
			{
				return this._ID_TRANGTHAIVANBAN_VANBANDEN;
			}
			set
			{
				if ((this._ID_TRANGTHAIVANBAN_VANBANDEN != value))
				{
					this.OnID_TRANGTHAIVANBAN_VANBANDENChanging(value);
					this.SendPropertyChanging();
					this._ID_TRANGTHAIVANBAN_VANBANDEN = value;
					this.SendPropertyChanged("ID_TRANGTHAIVANBAN_VANBANDEN");
					this.OnID_TRANGTHAIVANBAN_VANBANDENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TRANGTHAIVANBAN_VANBANDI", DbType="Int NOT NULL")]
		public int ID_TRANGTHAIVANBAN_VANBANDI
		{
			get
			{
				return this._ID_TRANGTHAIVANBAN_VANBANDI;
			}
			set
			{
				if ((this._ID_TRANGTHAIVANBAN_VANBANDI != value))
				{
					this.OnID_TRANGTHAIVANBAN_VANBANDIChanging(value);
					this.SendPropertyChanging();
					this._ID_TRANGTHAIVANBAN_VANBANDI = value;
					this.SendPropertyChanged("ID_TRANGTHAIVANBAN_VANBANDI");
					this.OnID_TRANGTHAIVANBAN_VANBANDIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TRANGTHAIVANBAN_VANBANNOIBO", DbType="Int NOT NULL")]
		public int ID_TRANGTHAIVANBAN_VANBANNOIBO
		{
			get
			{
				return this._ID_TRANGTHAIVANBAN_VANBANNOIBO;
			}
			set
			{
				if ((this._ID_TRANGTHAIVANBAN_VANBANNOIBO != value))
				{
					this.OnID_TRANGTHAIVANBAN_VANBANNOIBOChanging(value);
					this.SendPropertyChanging();
					this._ID_TRANGTHAIVANBAN_VANBANNOIBO = value;
					this.SendPropertyChanged("ID_TRANGTHAIVANBAN_VANBANNOIBO");
					this.OnID_TRANGTHAIVANBAN_VANBANNOIBOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VANBANDEN")]
	public partial class VANBANDEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_VanBanDen;
		
		private string _TenVanBanDen;
		
		private string _TrichYeuVanBanDen;
		
		private string _SoHieuGocVanBanDen;
		
		private System.DateTime _NgayVanBanDen;
		
		private System.DateTime _NgayBanHanhVanBanDen;
		
		private string _NoiLuuVanBanDen;
		
		private string _SoBanPhatHanhVanBanDen;
		
		private System.DateTime _NgayDuyetVanBanDen;
		
		private System.DateTime _NgayLuuSoVanBanDen;
		
		private string _NoiDungVanBanDen;
		
		private string _VanBanLienQuanVanBanDen;
		
		private int _ID_VANBANDEN_NGUOIDUNG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_VanBanDenChanging(int value);
    partial void OnID_VanBanDenChanged();
    partial void OnTenVanBanDenChanging(string value);
    partial void OnTenVanBanDenChanged();
    partial void OnTrichYeuVanBanDenChanging(string value);
    partial void OnTrichYeuVanBanDenChanged();
    partial void OnSoHieuGocVanBanDenChanging(string value);
    partial void OnSoHieuGocVanBanDenChanged();
    partial void OnNgayVanBanDenChanging(System.DateTime value);
    partial void OnNgayVanBanDenChanged();
    partial void OnNgayBanHanhVanBanDenChanging(System.DateTime value);
    partial void OnNgayBanHanhVanBanDenChanged();
    partial void OnNoiLuuVanBanDenChanging(string value);
    partial void OnNoiLuuVanBanDenChanged();
    partial void OnSoBanPhatHanhVanBanDenChanging(string value);
    partial void OnSoBanPhatHanhVanBanDenChanged();
    partial void OnNgayDuyetVanBanDenChanging(System.DateTime value);
    partial void OnNgayDuyetVanBanDenChanged();
    partial void OnNgayLuuSoVanBanDenChanging(System.DateTime value);
    partial void OnNgayLuuSoVanBanDenChanged();
    partial void OnNoiDungVanBanDenChanging(string value);
    partial void OnNoiDungVanBanDenChanged();
    partial void OnVanBanLienQuanVanBanDenChanging(string value);
    partial void OnVanBanLienQuanVanBanDenChanged();
    partial void OnID_VANBANDEN_NGUOIDUNGChanging(int value);
    partial void OnID_VANBANDEN_NGUOIDUNGChanged();
    #endregion
		
		public VANBANDEN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_VanBanDen", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_VanBanDen
		{
			get
			{
				return this._ID_VanBanDen;
			}
			set
			{
				if ((this._ID_VanBanDen != value))
				{
					this.OnID_VanBanDenChanging(value);
					this.SendPropertyChanging();
					this._ID_VanBanDen = value;
					this.SendPropertyChanged("ID_VanBanDen");
					this.OnID_VanBanDenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenVanBanDen", DbType="NChar(255) NOT NULL", CanBeNull=false)]
		public string TenVanBanDen
		{
			get
			{
				return this._TenVanBanDen;
			}
			set
			{
				if ((this._TenVanBanDen != value))
				{
					this.OnTenVanBanDenChanging(value);
					this.SendPropertyChanging();
					this._TenVanBanDen = value;
					this.SendPropertyChanged("TenVanBanDen");
					this.OnTenVanBanDenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrichYeuVanBanDen", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string TrichYeuVanBanDen
		{
			get
			{
				return this._TrichYeuVanBanDen;
			}
			set
			{
				if ((this._TrichYeuVanBanDen != value))
				{
					this.OnTrichYeuVanBanDenChanging(value);
					this.SendPropertyChanging();
					this._TrichYeuVanBanDen = value;
					this.SendPropertyChanged("TrichYeuVanBanDen");
					this.OnTrichYeuVanBanDenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoHieuGocVanBanDen", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string SoHieuGocVanBanDen
		{
			get
			{
				return this._SoHieuGocVanBanDen;
			}
			set
			{
				if ((this._SoHieuGocVanBanDen != value))
				{
					this.OnSoHieuGocVanBanDenChanging(value);
					this.SendPropertyChanging();
					this._SoHieuGocVanBanDen = value;
					this.SendPropertyChanged("SoHieuGocVanBanDen");
					this.OnSoHieuGocVanBanDenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayVanBanDen", DbType="DateTime NOT NULL")]
		public System.DateTime NgayVanBanDen
		{
			get
			{
				return this._NgayVanBanDen;
			}
			set
			{
				if ((this._NgayVanBanDen != value))
				{
					this.OnNgayVanBanDenChanging(value);
					this.SendPropertyChanging();
					this._NgayVanBanDen = value;
					this.SendPropertyChanged("NgayVanBanDen");
					this.OnNgayVanBanDenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBanHanhVanBanDen", DbType="Date NOT NULL")]
		public System.DateTime NgayBanHanhVanBanDen
		{
			get
			{
				return this._NgayBanHanhVanBanDen;
			}
			set
			{
				if ((this._NgayBanHanhVanBanDen != value))
				{
					this.OnNgayBanHanhVanBanDenChanging(value);
					this.SendPropertyChanging();
					this._NgayBanHanhVanBanDen = value;
					this.SendPropertyChanged("NgayBanHanhVanBanDen");
					this.OnNgayBanHanhVanBanDenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiLuuVanBanDen", DbType="NVarChar(255)")]
		public string NoiLuuVanBanDen
		{
			get
			{
				return this._NoiLuuVanBanDen;
			}
			set
			{
				if ((this._NoiLuuVanBanDen != value))
				{
					this.OnNoiLuuVanBanDenChanging(value);
					this.SendPropertyChanging();
					this._NoiLuuVanBanDen = value;
					this.SendPropertyChanged("NoiLuuVanBanDen");
					this.OnNoiLuuVanBanDenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBanPhatHanhVanBanDen", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string SoBanPhatHanhVanBanDen
		{
			get
			{
				return this._SoBanPhatHanhVanBanDen;
			}
			set
			{
				if ((this._SoBanPhatHanhVanBanDen != value))
				{
					this.OnSoBanPhatHanhVanBanDenChanging(value);
					this.SendPropertyChanging();
					this._SoBanPhatHanhVanBanDen = value;
					this.SendPropertyChanged("SoBanPhatHanhVanBanDen");
					this.OnSoBanPhatHanhVanBanDenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDuyetVanBanDen", DbType="DateTime NOT NULL")]
		public System.DateTime NgayDuyetVanBanDen
		{
			get
			{
				return this._NgayDuyetVanBanDen;
			}
			set
			{
				if ((this._NgayDuyetVanBanDen != value))
				{
					this.OnNgayDuyetVanBanDenChanging(value);
					this.SendPropertyChanging();
					this._NgayDuyetVanBanDen = value;
					this.SendPropertyChanged("NgayDuyetVanBanDen");
					this.OnNgayDuyetVanBanDenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLuuSoVanBanDen", DbType="DateTime NOT NULL")]
		public System.DateTime NgayLuuSoVanBanDen
		{
			get
			{
				return this._NgayLuuSoVanBanDen;
			}
			set
			{
				if ((this._NgayLuuSoVanBanDen != value))
				{
					this.OnNgayLuuSoVanBanDenChanging(value);
					this.SendPropertyChanging();
					this._NgayLuuSoVanBanDen = value;
					this.SendPropertyChanged("NgayLuuSoVanBanDen");
					this.OnNgayLuuSoVanBanDenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungVanBanDen", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string NoiDungVanBanDen
		{
			get
			{
				return this._NoiDungVanBanDen;
			}
			set
			{
				if ((this._NoiDungVanBanDen != value))
				{
					this.OnNoiDungVanBanDenChanging(value);
					this.SendPropertyChanging();
					this._NoiDungVanBanDen = value;
					this.SendPropertyChanged("NoiDungVanBanDen");
					this.OnNoiDungVanBanDenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VanBanLienQuanVanBanDen", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string VanBanLienQuanVanBanDen
		{
			get
			{
				return this._VanBanLienQuanVanBanDen;
			}
			set
			{
				if ((this._VanBanLienQuanVanBanDen != value))
				{
					this.OnVanBanLienQuanVanBanDenChanging(value);
					this.SendPropertyChanging();
					this._VanBanLienQuanVanBanDen = value;
					this.SendPropertyChanged("VanBanLienQuanVanBanDen");
					this.OnVanBanLienQuanVanBanDenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_VANBANDEN_NGUOIDUNG", DbType="Int NOT NULL")]
		public int ID_VANBANDEN_NGUOIDUNG
		{
			get
			{
				return this._ID_VANBANDEN_NGUOIDUNG;
			}
			set
			{
				if ((this._ID_VANBANDEN_NGUOIDUNG != value))
				{
					this.OnID_VANBANDEN_NGUOIDUNGChanging(value);
					this.SendPropertyChanging();
					this._ID_VANBANDEN_NGUOIDUNG = value;
					this.SendPropertyChanged("ID_VANBANDEN_NGUOIDUNG");
					this.OnID_VANBANDEN_NGUOIDUNGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VANBANDI")]
	public partial class VANBANDI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_VanBanDi;
		
		private string _TenVanBanDi;
		
		private string _TrichYeuVanBanDi;
		
		private string _SoHieuGocVanBanDi;
		
		private System.DateTime _NgayVanBanDi;
		
		private System.DateTime _NgayBanHanhVanBanDi;
		
		private string _NoiLuuVanBanDi;
		
		private string _SoBanPhatHanhVanBanDi;
		
		private System.DateTime _NgayDuyetVanBanDi;
		
		private System.DateTime _NgayLuuSoVanBanDi;
		
		private string _NoiDungVanBanDi;
		
		private string _VanBanLienQuanVanBanDi;
		
		private int _ID_VANBANDI_NGUOIDUNG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_VanBanDiChanging(int value);
    partial void OnID_VanBanDiChanged();
    partial void OnTenVanBanDiChanging(string value);
    partial void OnTenVanBanDiChanged();
    partial void OnTrichYeuVanBanDiChanging(string value);
    partial void OnTrichYeuVanBanDiChanged();
    partial void OnSoHieuGocVanBanDiChanging(string value);
    partial void OnSoHieuGocVanBanDiChanged();
    partial void OnNgayVanBanDiChanging(System.DateTime value);
    partial void OnNgayVanBanDiChanged();
    partial void OnNgayBanHanhVanBanDiChanging(System.DateTime value);
    partial void OnNgayBanHanhVanBanDiChanged();
    partial void OnNoiLuuVanBanDiChanging(string value);
    partial void OnNoiLuuVanBanDiChanged();
    partial void OnSoBanPhatHanhVanBanDiChanging(string value);
    partial void OnSoBanPhatHanhVanBanDiChanged();
    partial void OnNgayDuyetVanBanDiChanging(System.DateTime value);
    partial void OnNgayDuyetVanBanDiChanged();
    partial void OnNgayLuuSoVanBanDiChanging(System.DateTime value);
    partial void OnNgayLuuSoVanBanDiChanged();
    partial void OnNoiDungVanBanDiChanging(string value);
    partial void OnNoiDungVanBanDiChanged();
    partial void OnVanBanLienQuanVanBanDiChanging(string value);
    partial void OnVanBanLienQuanVanBanDiChanged();
    partial void OnID_VANBANDI_NGUOIDUNGChanging(int value);
    partial void OnID_VANBANDI_NGUOIDUNGChanged();
    #endregion
		
		public VANBANDI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_VanBanDi", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_VanBanDi
		{
			get
			{
				return this._ID_VanBanDi;
			}
			set
			{
				if ((this._ID_VanBanDi != value))
				{
					this.OnID_VanBanDiChanging(value);
					this.SendPropertyChanging();
					this._ID_VanBanDi = value;
					this.SendPropertyChanged("ID_VanBanDi");
					this.OnID_VanBanDiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenVanBanDi", DbType="NChar(255) NOT NULL", CanBeNull=false)]
		public string TenVanBanDi
		{
			get
			{
				return this._TenVanBanDi;
			}
			set
			{
				if ((this._TenVanBanDi != value))
				{
					this.OnTenVanBanDiChanging(value);
					this.SendPropertyChanging();
					this._TenVanBanDi = value;
					this.SendPropertyChanged("TenVanBanDi");
					this.OnTenVanBanDiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrichYeuVanBanDi", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string TrichYeuVanBanDi
		{
			get
			{
				return this._TrichYeuVanBanDi;
			}
			set
			{
				if ((this._TrichYeuVanBanDi != value))
				{
					this.OnTrichYeuVanBanDiChanging(value);
					this.SendPropertyChanging();
					this._TrichYeuVanBanDi = value;
					this.SendPropertyChanged("TrichYeuVanBanDi");
					this.OnTrichYeuVanBanDiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoHieuGocVanBanDi", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string SoHieuGocVanBanDi
		{
			get
			{
				return this._SoHieuGocVanBanDi;
			}
			set
			{
				if ((this._SoHieuGocVanBanDi != value))
				{
					this.OnSoHieuGocVanBanDiChanging(value);
					this.SendPropertyChanging();
					this._SoHieuGocVanBanDi = value;
					this.SendPropertyChanged("SoHieuGocVanBanDi");
					this.OnSoHieuGocVanBanDiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayVanBanDi", DbType="DateTime NOT NULL")]
		public System.DateTime NgayVanBanDi
		{
			get
			{
				return this._NgayVanBanDi;
			}
			set
			{
				if ((this._NgayVanBanDi != value))
				{
					this.OnNgayVanBanDiChanging(value);
					this.SendPropertyChanging();
					this._NgayVanBanDi = value;
					this.SendPropertyChanged("NgayVanBanDi");
					this.OnNgayVanBanDiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBanHanhVanBanDi", DbType="Date NOT NULL")]
		public System.DateTime NgayBanHanhVanBanDi
		{
			get
			{
				return this._NgayBanHanhVanBanDi;
			}
			set
			{
				if ((this._NgayBanHanhVanBanDi != value))
				{
					this.OnNgayBanHanhVanBanDiChanging(value);
					this.SendPropertyChanging();
					this._NgayBanHanhVanBanDi = value;
					this.SendPropertyChanged("NgayBanHanhVanBanDi");
					this.OnNgayBanHanhVanBanDiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiLuuVanBanDi", DbType="NVarChar(255)")]
		public string NoiLuuVanBanDi
		{
			get
			{
				return this._NoiLuuVanBanDi;
			}
			set
			{
				if ((this._NoiLuuVanBanDi != value))
				{
					this.OnNoiLuuVanBanDiChanging(value);
					this.SendPropertyChanging();
					this._NoiLuuVanBanDi = value;
					this.SendPropertyChanged("NoiLuuVanBanDi");
					this.OnNoiLuuVanBanDiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBanPhatHanhVanBanDi", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string SoBanPhatHanhVanBanDi
		{
			get
			{
				return this._SoBanPhatHanhVanBanDi;
			}
			set
			{
				if ((this._SoBanPhatHanhVanBanDi != value))
				{
					this.OnSoBanPhatHanhVanBanDiChanging(value);
					this.SendPropertyChanging();
					this._SoBanPhatHanhVanBanDi = value;
					this.SendPropertyChanged("SoBanPhatHanhVanBanDi");
					this.OnSoBanPhatHanhVanBanDiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDuyetVanBanDi", DbType="DateTime NOT NULL")]
		public System.DateTime NgayDuyetVanBanDi
		{
			get
			{
				return this._NgayDuyetVanBanDi;
			}
			set
			{
				if ((this._NgayDuyetVanBanDi != value))
				{
					this.OnNgayDuyetVanBanDiChanging(value);
					this.SendPropertyChanging();
					this._NgayDuyetVanBanDi = value;
					this.SendPropertyChanged("NgayDuyetVanBanDi");
					this.OnNgayDuyetVanBanDiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayLuuSoVanBanDi", DbType="DateTime NOT NULL")]
		public System.DateTime NgayLuuSoVanBanDi
		{
			get
			{
				return this._NgayLuuSoVanBanDi;
			}
			set
			{
				if ((this._NgayLuuSoVanBanDi != value))
				{
					this.OnNgayLuuSoVanBanDiChanging(value);
					this.SendPropertyChanging();
					this._NgayLuuSoVanBanDi = value;
					this.SendPropertyChanged("NgayLuuSoVanBanDi");
					this.OnNgayLuuSoVanBanDiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungVanBanDi", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string NoiDungVanBanDi
		{
			get
			{
				return this._NoiDungVanBanDi;
			}
			set
			{
				if ((this._NoiDungVanBanDi != value))
				{
					this.OnNoiDungVanBanDiChanging(value);
					this.SendPropertyChanging();
					this._NoiDungVanBanDi = value;
					this.SendPropertyChanged("NoiDungVanBanDi");
					this.OnNoiDungVanBanDiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VanBanLienQuanVanBanDi", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string VanBanLienQuanVanBanDi
		{
			get
			{
				return this._VanBanLienQuanVanBanDi;
			}
			set
			{
				if ((this._VanBanLienQuanVanBanDi != value))
				{
					this.OnVanBanLienQuanVanBanDiChanging(value);
					this.SendPropertyChanging();
					this._VanBanLienQuanVanBanDi = value;
					this.SendPropertyChanged("VanBanLienQuanVanBanDi");
					this.OnVanBanLienQuanVanBanDiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_VANBANDI_NGUOIDUNG", DbType="Int NOT NULL")]
		public int ID_VANBANDI_NGUOIDUNG
		{
			get
			{
				return this._ID_VANBANDI_NGUOIDUNG;
			}
			set
			{
				if ((this._ID_VANBANDI_NGUOIDUNG != value))
				{
					this.OnID_VANBANDI_NGUOIDUNGChanging(value);
					this.SendPropertyChanging();
					this._ID_VANBANDI_NGUOIDUNG = value;
					this.SendPropertyChanged("ID_VANBANDI_NGUOIDUNG");
					this.OnID_VANBANDI_NGUOIDUNGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
